/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dsms.views;

import dsms.common_classes.CalculationMaker;
import dsms.controllers.RegistrationController;
import dsms.controllers.StudentController;
import dsms.controllers.TrialDetailController;
import dsms.models.Registration;
import dsms.models.Student;
import dsms.models.TrialDetail;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Alerts extends javax.swing.JDialog {

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    String date;

    /**
     * Creates new form Alerts
     */
    public Alerts(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Students with incomplete payments");
        setLocationRelativeTo(null);
        dateChooser.setDate(new Date());
        date = sdf.format(dateChooser.getDate());
        noDebtLabel.setVisible(false);
        noDebtLabel1.setVisible(false);
        try {
            boolean bool = addDataToTable(pendingsTable, date);
            if (!bool) {
                noDebtLabel1.setVisible(true);
            }
            boolean bool1 = addDataToTable(todayPendingsTable, sdf.format(new Date()));
            if (!bool1) {
                noDebtLabel1.setVisible(true);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Alerts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private boolean addDataToTable(JTable table, String date) throws ClassNotFoundException, SQLException {
        boolean bool;
        ArrayList<TrialDetail> trialPendings = TrialDetailController.searchTrialPendingList(date);
        if (trialPendings.isEmpty()) {
            bool = false;
        } else {
            DefaultTableModel dtm = (DefaultTableModel) table.getModel();
            for (TrialDetail trialDetail : trialPendings) {
                double paidTotal = CalculationMaker.paymentsAdder(trialDetail.getRegistrationId());
                Registration registration = RegistrationController.searchRegistration(trialDetail.getRegistrationId());
                Student student = StudentController.searchStudent(registration.getStudentId());
                double balance = registration.getTotalFee() - registration.getDiscount() - paidTotal;
                dtm.addRow(new Object[]{student.getStudentId(), registration.getRegistrationId(), student.getNameWithInitials(), trialDetail.getDate(), balance});
            }
            bool = true;
        }
        return bool;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        todayPendingsTable = new javax.swing.JTable();
        reloadButton = new javax.swing.JButton();
        noDebtLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        reloadAnyButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        pendingsTable = new javax.swing.JTable();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        noDebtLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        todayPendingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stu.ID", "Reg.ID", "Name", "Trial Date", "BalanceToPay"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        todayPendingsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(todayPendingsTable);
        todayPendingsTable.getColumnModel().getColumn(0).setPreferredWidth(5);
        todayPendingsTable.getColumnModel().getColumn(1).setPreferredWidth(5);
        todayPendingsTable.getColumnModel().getColumn(4).setPreferredWidth(40);

        reloadButton.setText("RELOAD");
        reloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadButtonActionPerformed(evt);
            }
        });

        noDebtLabel.setFont(new java.awt.Font("Swis721 Lt BT", 1, 11)); // NOI18N
        noDebtLabel.setForeground(new java.awt.Color(51, 0, 204));
        noDebtLabel.setText("No Debts Available");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(reloadButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 13, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(noDebtLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(noDebtLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(reloadButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Today", jPanel1);

        reloadAnyButton.setText("RELOAD");
        reloadAnyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reloadAnyButtonActionPerformed(evt);
            }
        });

        pendingsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Stu.ID", "Reg.ID", "Name", "Trial Date", "BalanceToPay"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        pendingsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(pendingsTable);
        pendingsTable.getColumnModel().getColumn(0).setPreferredWidth(5);
        pendingsTable.getColumnModel().getColumn(1).setPreferredWidth(5);
        pendingsTable.getColumnModel().getColumn(4).setPreferredWidth(40);

        dateChooser.setDateFormatString("yyyy-MM-dd");

        jLabel1.setText("Select date:");

        noDebtLabel1.setFont(new java.awt.Font("Swis721 Lt BT", 1, 11)); // NOI18N
        noDebtLabel1.setForeground(new java.awt.Color(51, 0, 204));
        noDebtLabel1.setText("No Debts Available");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(reloadAnyButton))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 13, Short.MAX_VALUE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(noDebtLabel1)
                .addGap(110, 110, 110))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(noDebtLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(reloadAnyButton)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Search by date", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Today");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadButtonActionPerformed
        try {
            boolean bool = addDataToTable(pendingsTable, date);
            if (!bool) {
                noDebtLabel1.setVisible(true);
            }
            boolean bool1 = addDataToTable(todayPendingsTable, sdf.format(new Date()));
            if (!bool1) {
                noDebtLabel1.setVisible(true);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Alerts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_reloadButtonActionPerformed

    private void reloadAnyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reloadAnyButtonActionPerformed
        try {
            boolean bool = addDataToTable(pendingsTable, date);
            if (!bool) {
                noDebtLabel1.setVisible(true);
            }
            boolean bool1 = addDataToTable(todayPendingsTable, sdf.format(new Date()));
            if (!bool1) {
                noDebtLabel1.setVisible(true);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(Alerts.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_reloadAnyButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alerts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Alerts dialog = new Alerts(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel noDebtLabel;
    private javax.swing.JLabel noDebtLabel1;
    private javax.swing.JTable pendingsTable;
    private javax.swing.JButton reloadAnyButton;
    private javax.swing.JButton reloadButton;
    private javax.swing.JTable todayPendingsTable;
    // End of variables declaration//GEN-END:variables
}
