/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dsms.views;

import dsms.common_classes.CalculationMaker;
import dsms.common_classes.ComboItemsAdder;
import dsms.controllers.*;
import dsms.models.*;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class ExamTrialDetail extends javax.swing.JInternalFrame {

    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    DefaultTableModel dtmExamDate, dtmExamResult, dtmTrialResult,dtmTrialDate;

    /**
     * Creates new form ExamTrialDetail
     */
    public ExamTrialDetail() {
        initComponents();
        setTitle("Exam And Trial Details Manager");
        try {
            //ComboItemsAdder.getStudentsOfTrial(studentCombo2);
            ComboItemsAdder.getStudentsOfExam(enterExamDateCombo);
            ComboItemsAdder.getStudentsOfTrial(enterTrialDateCombo);
            ComboItemsAdder.getStudentsOfExamResult(enterExamResultCombo);
            ComboItemsAdder.getStudentsOfTrialResult(enterTrialResultCombo);
            alreadyLabel.setVisible(false);
            alreadyLabel1.setVisible(false);
             alreadyLabel2.setVisible(false);
            alreadyTrialLabel.setVisible(false);
            examDateChooser.setDate(new Date());
            examRDateChooser.setDate(new Date());
            trialDateChooser.setDate(new Date());
            trialDateChooser1.setDate(new Date());
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ExamTrialDetail.class.getName()).log(Level.SEVERE, null, ex);
        }


    }
public void requestFocusForm(){
   examDateChooser.requestFocus();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        examDateChooser = new com.toedter.calendar.JDateChooser();
        jPanel13 = new javax.swing.JPanel();
        nicLabel = new javax.swing.JLabel();
        enterExamDateCombo = new javax.swing.JComboBox();
        addButton = new javax.swing.JButton();
        ridText = new javax.swing.JTextField();
        attemptText = new javax.swing.JTextField();
        nameText = new javax.swing.JTextField();
        alreadyLabel = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        examDateTable = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        examRDateChooser = new com.toedter.calendar.JDateChooser();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        enterExamResultCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        passedRButton = new javax.swing.JRadioButton();
        failedRButton = new javax.swing.JRadioButton();
        alreadyLabel1 = new javax.swing.JLabel();
        addButton1 = new javax.swing.JButton();
        ridText1 = new javax.swing.JTextField();
        nameText1 = new javax.swing.JTextField();
        attemptText1 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        examResultTable = new javax.swing.JTable();
        jPanel16 = new javax.swing.JPanel();
        saveButton1 = new javax.swing.JButton();
        exitButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        trialDateChooser = new com.toedter.calendar.JDateChooser();
        jPanel10 = new javax.swing.JPanel();
        enterTrialResultCombo = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        alreadyTrialLabel = new javax.swing.JLabel();
        addTrialButton = new javax.swing.JButton();
        ridText2 = new javax.swing.JTextField();
        nameText2 = new javax.swing.JTextField();
        attemptText2 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        trialResultTable = new javax.swing.JTable();
        jPanel17 = new javax.swing.JPanel();
        saveButton2 = new javax.swing.JButton();
        exitButton2 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        trialDateChooser1 = new com.toedter.calendar.JDateChooser();
        jPanel20 = new javax.swing.JPanel();
        nicLabel1 = new javax.swing.JLabel();
        enterTrialDateCombo = new javax.swing.JComboBox();
        addTrialDateButton = new javax.swing.JButton();
        ridText3 = new javax.swing.JTextField();
        attemptText3 = new javax.swing.JTextField();
        nameText3 = new javax.swing.JTextField();
        alreadyLabel2 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        trialDateTable = new javax.swing.JTable();
        jPanel22 = new javax.swing.JPanel();
        saveButton3 = new javax.swing.JButton();
        exitButton3 = new javax.swing.JButton();

        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Date:");

        examDateChooser.setDateFormatString("yyyy-MM-dd");
        examDateChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                examDateChooserPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(examDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(examDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nicLabel.setText("Registraton ID:");

        enterExamDateCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                enterExamDateComboItemStateChanged(evt);
            }
        });
        enterExamDateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterExamDateComboActionPerformed(evt);
            }
        });

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Plus.png"))); // NOI18N
        addButton.setText("ADD");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        ridText.setEditable(false);

        attemptText.setEditable(false);

        nameText.setEditable(false);

        alreadyLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        alreadyLabel.setForeground(new java.awt.Color(255, 0, 0));
        alreadyLabel.setText("Already Added!");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(nicLabel)
                .addGap(22, 22, 22)
                .addComponent(enterExamDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ridText, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(attemptText, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(198, 198, 198)
                .addComponent(addButton)
                .addGap(18, 18, 18)
                .addComponent(alreadyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nicLabel)
                    .addComponent(enterExamDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ridText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attemptText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(alreadyLabel))
                .addContainerGap())
        );

        examDateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "RegistrationID", "NIC", "Name", "Attempt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        examDateTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(examDateTable);
        examDateTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        examDateTable.getColumnModel().getColumn(1).setPreferredWidth(20);
        examDateTable.getColumnModel().getColumn(3).setPreferredWidth(120);
        examDateTable.getColumnModel().getColumn(4).setPreferredWidth(5);

        jPanel15.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel15.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Save.png"))); // NOI18N
        saveButton.setText("SAVE");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel15.add(saveButton);

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exitButton.setText("EXIT");
        jPanel15.add(exitButton);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3)
            .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Enter exam dates", new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/to_do_list.png")), jPanel1); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Date:");

        examRDateChooser.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(examRDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(examRDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("NIC:");

        enterExamResultCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterExamResultComboActionPerformed(evt);
            }
        });

        jLabel3.setText("Result:");

        buttonGroup1.add(passedRButton);
        passedRButton.setSelected(true);
        passedRButton.setText("Passed");

        buttonGroup1.add(failedRButton);
        failedRButton.setText("Failed");

        alreadyLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        alreadyLabel1.setForeground(new java.awt.Color(255, 0, 0));
        alreadyLabel1.setText("Already Added!");

        addButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Plus.png"))); // NOI18N
        addButton1.setText("ADD");
        addButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton1ActionPerformed(evt);
            }
        });

        ridText1.setEditable(false);

        nameText1.setEditable(false);

        attemptText1.setEditable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(passedRButton)
                        .addGap(18, 18, 18)
                        .addComponent(failedRButton)
                        .addGap(42, 42, 42)
                        .addComponent(addButton1)
                        .addGap(18, 18, 18)
                        .addComponent(alreadyLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(enterExamResultCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ridText1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameText1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(attemptText1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ridText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nameText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(attemptText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(enterExamResultCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addButton1)
                        .addComponent(alreadyLabel1))
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(passedRButton)
                        .addComponent(failedRButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        examResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "RegistrationId", "NIC no.", "Name", "Attempt", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        examResultTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(examResultTable);
        examResultTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        examResultTable.getColumnModel().getColumn(1).setPreferredWidth(10);
        examResultTable.getColumnModel().getColumn(3).setPreferredWidth(150);
        examResultTable.getColumnModel().getColumn(4).setPreferredWidth(5);
        examResultTable.getColumnModel().getColumn(5).setPreferredWidth(20);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel16.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        saveButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Save.png"))); // NOI18N
        saveButton1.setText("SAVE");
        saveButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton1ActionPerformed(evt);
            }
        });
        jPanel16.add(saveButton1);

        exitButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exitButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Cancel.png"))); // NOI18N
        exitButton1.setText("EXIT");
        jPanel16.add(exitButton1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Enter exam results", new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/to_do_list_cheked_all.png")), jPanel2); // NOI18N

        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Date:");

        trialDateChooser.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trialDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trialDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        enterTrialResultCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterTrialResultComboActionPerformed(evt);
            }
        });

        jLabel6.setText("Result:");

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setText("Passed");

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setText("Failed");

        jLabel7.setText("NIC:");

        alreadyTrialLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        alreadyTrialLabel.setForeground(new java.awt.Color(255, 0, 0));
        alreadyTrialLabel.setText("Already Added!");

        addTrialButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Plus.png"))); // NOI18N
        addTrialButton.setText("ADD");
        addTrialButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrialButtonActionPerformed(evt);
            }
        });

        ridText2.setEditable(false);

        nameText2.setEditable(false);

        attemptText2.setEditable(false);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jRadioButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton4)
                        .addGap(27, 27, 27)
                        .addComponent(addTrialButton)
                        .addGap(18, 18, 18)
                        .addComponent(alreadyTrialLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(enterTrialResultCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ridText2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameText2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(attemptText2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enterTrialResultCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(ridText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attemptText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addTrialButton)
                        .addComponent(alreadyTrialLabel))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jRadioButton3)
                        .addComponent(jRadioButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        trialResultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "RegistrationId", "NIC no.", "Name", "Attempt", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        trialResultTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(trialResultTable);
        trialResultTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        trialResultTable.getColumnModel().getColumn(1).setPreferredWidth(10);
        trialResultTable.getColumnModel().getColumn(3).setPreferredWidth(150);
        trialResultTable.getColumnModel().getColumn(4).setPreferredWidth(5);
        trialResultTable.getColumnModel().getColumn(5).setPreferredWidth(20);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jPanel17.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel17.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        saveButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Save.png"))); // NOI18N
        saveButton2.setText("SAVE");
        saveButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton2ActionPerformed(evt);
            }
        });
        jPanel17.add(saveButton2);

        exitButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exitButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Cancel.png"))); // NOI18N
        exitButton2.setText("EXIT");
        jPanel17.add(exitButton2);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(137, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Enter trial resluts", new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/to_do_list.png")), jPanel3); // NOI18N

        jPanel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel8.setText("Date:");

        trialDateChooser1.setDateFormatString("yyyy-MM-dd");
        trialDateChooser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                trialDateChooser1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(trialDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(443, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(trialDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nicLabel1.setText("NIC:");

        enterTrialDateCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                enterTrialDateComboItemStateChanged(evt);
            }
        });
        enterTrialDateCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterTrialDateComboActionPerformed(evt);
            }
        });

        addTrialDateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Plus.png"))); // NOI18N
        addTrialDateButton.setText("ADD");
        addTrialDateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTrialDateButtonActionPerformed(evt);
            }
        });

        ridText3.setEditable(false);

        attemptText3.setEditable(false);

        nameText3.setEditable(false);

        alreadyLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        alreadyLabel2.setForeground(new java.awt.Color(255, 0, 0));
        alreadyLabel2.setText("Already Added!");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(nicLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(enterTrialDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ridText3, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameText3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(attemptText3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(addTrialDateButton)
                        .addGap(18, 18, 18)
                        .addComponent(alreadyLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nicLabel1)
                    .addComponent(enterTrialDateCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ridText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(attemptText3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addTrialDateButton)
                    .addComponent(alreadyLabel2))
                .addContainerGap())
        );

        trialDateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "RegistrationID", "NIC", "Name", "Attempt"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        trialDateTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(trialDateTable);
        trialDateTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        trialDateTable.getColumnModel().getColumn(1).setPreferredWidth(20);
        trialDateTable.getColumnModel().getColumn(3).setPreferredWidth(120);
        trialDateTable.getColumnModel().getColumn(4).setPreferredWidth(5);

        jPanel22.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel22.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        saveButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Save.png"))); // NOI18N
        saveButton3.setText("SAVE");
        saveButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButton3ActionPerformed(evt);
            }
        });
        jPanel22.add(saveButton3);

        exitButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exitButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Cancel.png"))); // NOI18N
        exitButton3.setText("EXIT");
        jPanel22.add(exitButton3);

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5)
            .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Enter trial dates", new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/to_do_list_cheked_all.png")), jPanel18); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterExamDateComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_enterExamDateComboItemStateChanged
    }//GEN-LAST:event_enterExamDateComboItemStateChanged

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed


        alreadyLabel.setVisible(false);
        String examDate = sdf.format(examDateChooser.getDate());
        String regID = ridText.getText();
        String nicAndClass = enterExamDateCombo.getSelectedItem().toString();
        StringTokenizer st = new StringTokenizer(nicAndClass, "_");//default delimiter
        String nic = st.nextToken();
        String name = nameText.getText();
        String attempt = attemptText.getText();
        dtmExamDate = (DefaultTableModel) examDateTable.getModel();
        int sameRow = 0;

        if (dtmExamDate.getRowCount() > 0) {
            for (int i = 0; i < dtmExamDate.getRowCount(); i++) {
                if (examDate.equals(dtmExamDate.getValueAt(i, 0).toString())
                        & regID.equals(dtmExamDate.getValueAt(i, 1).toString())
                        & nic.equals(dtmExamDate.getValueAt(i, 2).toString())
                        & name.equals(dtmExamDate.getValueAt(i, 3).toString())
                        & attempt.equals(dtmExamDate.getValueAt(i, 4).toString())) {
                    sameRow++;
                }
            }
            if (sameRow == 0) {

                dtmExamDate.addRow(new Object[]{examDate, regID, nic, name, attempt});
                enterExamDateCombo.removeItem(nicAndClass);
                alreadyLabel.setVisible(false);
            } else {
                alreadyLabel.setVisible(true);
            }
            sameRow = 0;
        } else if (dtmExamDate.getRowCount() == 0) {
            dtmExamDate.addRow(new Object[]{examDate, regID, nic, name, attempt});
            enterExamDateCombo.removeItem(nicAndClass);
            alreadyLabel.setVisible(false);
        }
//         try { //enterExamDateCombo.removeAllItems();
//             ComboItemsAdder.getStudentsOfExam(enterExamDateCombo);
//             System.out.println("sdf");
//        } catch (SQLException | ClassNotFoundException ex) {
//            Logger.getLogger(ExamTrialDetail.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            for (int i = 0; i < dtmExamDate.getRowCount(); i++) {
                try {
                    ExamDetail examDetail = new ExamDetail(dtmExamDate.getValueAt(i, 1).toString(), Integer.parseInt(dtmExamDate.getValueAt(i, 4).toString()), dtmExamDate.getValueAt(i, 0).toString());
                    ExamDetailController.addExamDetail(examDetail);
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(ExamTrialDetail.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            // enterExamDateCombo.removeAllItems();
            dtmExamDate.setRowCount(0);
            ComboItemsAdder.getStudentsOfExam(enterExamDateCombo);
            ComboItemsAdder.getStudentsOfTrial(enterTrialDateCombo);
            ComboItemsAdder.getStudentsOfExamResult(enterExamResultCombo);
            ComboItemsAdder.getStudentsOfTrialResult(enterTrialResultCombo);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ExamTrialDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void enterExamDateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterExamDateComboActionPerformed
        if (enterExamDateCombo.getSelectedItem() != null) {
            try {
                alreadyLabel.setVisible(false);
                String nicAndClass = enterExamDateCombo.getSelectedItem().toString();


                StringTokenizer st = new StringTokenizer(nicAndClass, "_");//default delimiter
                String nic = st.nextToken();
                String classType = st.nextToken();

                Student student = StudentController.searchStudentByNic(nic);
                VehicleClassSet vcs = VehicleClassController.searchVehicleClassSetByName(classType);
                Registration registration = RegistrationController.searchRegistration(student.getStudentId(), vcs.getClassId());
                ridText.setText(registration.getRegistrationId());
                nameText.setText(student.getNameWithInitials());
                ExamDetail examDetail = ExamDetailController.searchLastExamResult(registration.getRegistrationId());
                if (examDetail != null) {
                    attemptText.setText(Integer.toString(examDetail.getAttempt() + 1));
                } else {
                    attemptText.setText(Integer.toString(1));
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ExamTrialDetail.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_enterExamDateComboActionPerformed

    private void addButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton1ActionPerformed

        alreadyLabel1.setVisible(false);
        String examDate = sdf.format(examRDateChooser.getDate());
        String regID = ridText1.getText();
        String nicAndClass = enterExamResultCombo.getSelectedItem().toString();
        StringTokenizer st = new StringTokenizer(nicAndClass, "_");//default delimiter
        String nic = st.nextToken();
        String name = nameText1.getText();
        String attempt = attemptText1.getText();
        String result;
        if (buttonGroup1.getSelection() == passedRButton.getModel()) {
            result = "Passed";
        } else {
            result = "Failed";
        }
        dtmExamResult = (DefaultTableModel) examResultTable.getModel();
        int sameRow = 0;

        if (dtmExamResult.getRowCount() > 0) {
            for (int i = 0; i < dtmExamResult.getRowCount(); i++) {
                if (examDate.equals(dtmExamResult.getValueAt(i, 0).toString())
                        & regID.equals(dtmExamResult.getValueAt(i, 1).toString())
                        & nic.equals(dtmExamResult.getValueAt(i, 2).toString())
                        & name.equals(dtmExamResult.getValueAt(i, 3).toString())
                        & attempt.equals(dtmExamResult.getValueAt(i, 4).toString())
                        & result.equals(dtmExamResult.getValueAt(i, 5).toString())) {
                    sameRow++;
                }
            }
            if (sameRow == 0) {

                dtmExamResult.addRow(new Object[]{examDate, regID, nic, name, attempt, result});
                enterExamResultCombo.removeItem(nicAndClass);
                alreadyLabel1.setVisible(false);
            } else {
                alreadyLabel1.setVisible(true);
            }
            sameRow = 0;
        } else if (dtmExamResult.getRowCount() == 0) {
            dtmExamResult.addRow(new Object[]{examDate, regID, nic, name, attempt, result});
            enterExamResultCombo.removeItem(nicAndClass);
            alreadyLabel1.setVisible(false);
        }
    }//GEN-LAST:event_addButton1ActionPerformed

    private void addTrialButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrialButtonActionPerformed
        alreadyTrialLabel.setVisible(false);
        String trialDate = sdf.format(trialDateChooser.getDate());
        String regID = ridText2.getText();
        String nicAndClass = enterTrialResultCombo.getSelectedItem().toString();
        StringTokenizer st = new StringTokenizer(nicAndClass, "_");//default delimiter
        String nic = st.nextToken();
        String name = nameText2.getText();
        String attempt = attemptText2.getText();
        String result;
        if (buttonGroup2.getSelection() == passedRButton.getModel()) {
            result = "Passed";
        } else {
            result = "Failed";
        }
        dtmTrialResult = (DefaultTableModel) trialResultTable.getModel();
        int sameRow = 0;

        if (dtmTrialResult.getRowCount() > 0) {
            for (int i = 0; i < dtmTrialResult.getRowCount(); i++) {
                if (trialDate.equals(dtmTrialResult.getValueAt(i, 0).toString())
                        & regID.equals(dtmTrialResult.getValueAt(i, 1).toString())
                        & nic.equals(dtmTrialResult.getValueAt(i, 2).toString())
                        & name.equals(dtmTrialResult.getValueAt(i, 3).toString())
                        & attempt.equals(dtmTrialResult.getValueAt(i, 4).toString())
                        & result.equals(dtmTrialResult.getValueAt(i, 5).toString())) {
                    sameRow++;
                }
            }
            if (sameRow == 0) {

                dtmTrialResult.addRow(new Object[]{trialDate, regID, nic, name, attempt, result});
                enterTrialResultCombo.removeItem(nicAndClass);
                alreadyLabel1.setVisible(false);
            } else {
                alreadyLabel1.setVisible(true);
            }
            sameRow = 0;
        } else if (dtmTrialResult.getRowCount() == 0) {
            dtmTrialResult.addRow(new Object[]{trialDate, regID, nic, name, attempt, result});
            enterTrialResultCombo.removeItem(nicAndClass);
            alreadyLabel1.setVisible(false);
        }
    }//GEN-LAST:event_addTrialButtonActionPerformed

    private void enterExamResultComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterExamResultComboActionPerformed
        if (enterExamResultCombo.getSelectedItem() != null) {
            try {
                alreadyLabel1.setVisible(false);
                String nicAndClass = enterExamResultCombo.getSelectedItem().toString();
                StringTokenizer st = new StringTokenizer(nicAndClass, "_");
                String nic = st.nextToken();
                String classType = st.nextToken();

                Student student = StudentController.searchStudentByNic(nic);
                VehicleClassSet vcs = VehicleClassController.searchVehicleClassSetByName(classType);
                Registration registration = RegistrationController.searchRegistration(student.getStudentId(), vcs.getClassId());
                ridText1.setText(registration.getRegistrationId());
                nameText1.setText(student.getNameWithInitials());
                ExamDetail examDetail = ExamDetailController.searchLastExamDetail(registration.getRegistrationId());
                if (examDetail != null) {
                    attemptText1.setText(Integer.toString(examDetail.getAttempt()));
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ExamTrialDetail.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_enterExamResultComboActionPerformed

    private void saveButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton1ActionPerformed
        try {
            dtmExamResult = (DefaultTableModel) examResultTable.getModel();
            for (int i = 0; i < dtmExamResult.getRowCount(); i++) {
                try {
                    String resultTxt = dtmExamResult.getValueAt(i, 5).toString();
                    int result = 0;
                    switch (resultTxt) {
                        case "Passed":
                            result = 1;
                            break;
                        case "Failed":
                            result = -1;
                            break;
                    }
                    
                    ExamDetail examDetail = new ExamDetail(dtmExamResult.getValueAt(i, 1).toString(), Integer.parseInt(dtmExamResult.getValueAt(i, 4).toString()), dtmExamResult.getValueAt(i, 0).toString(), result);
                    ExamDetailController.addExamDetailResult(examDetail);
                    if (examDetail.getResult() == 1) {
                        String trialDate = CalculationMaker.addMonthsToDate(dtmExamResult.getValueAt(i, 0).toString(), 3);
                        TrialDetail trialDetail = new TrialDetail(dtmExamResult.getValueAt(i, 1).toString(), 1, trialDate);
                        TrialDetailController.addTrialDetail(trialDetail);
                    }
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(ExamTrialDetail.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            // enterExamDateCombo.removeAllItems();
            dtmExamResult.setRowCount(0);

            ComboItemsAdder.getStudentsOfExam(enterExamDateCombo);
            ComboItemsAdder.getStudentsOfTrial(enterTrialDateCombo);
            ComboItemsAdder.getStudentsOfExamResult(enterExamResultCombo);
            ComboItemsAdder.getStudentsOfTrialResult(enterTrialResultCombo);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ExamTrialDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButton1ActionPerformed

    private void saveButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton2ActionPerformed
        try {
            dtmTrialResult = (DefaultTableModel) trialResultTable.getModel();
            for (int i = 0; i < dtmTrialResult.getRowCount(); i++) {
                try {
                    String resultTxt = dtmTrialResult.getValueAt(i, 5).toString();
                    int result = 0;
                    switch (resultTxt) {
                        case "Passed":
                            result = 1;
                            break;
                        case "Failed":
                            result = -1;
                            break;
                    }

                   
                    TrialDetail trialDetail = new TrialDetail(dtmTrialResult.getValueAt(i, 1).toString(), Integer.parseInt(dtmTrialResult.getValueAt(i, 4).toString()), dtmTrialResult.getValueAt(i, 0).toString(), result);
                    int res = TrialDetailController.addTrialDetailResult(trialDetail);
                    if (res > 0) {
                        JOptionPane.showMessageDialog(this, "Saved");
                    }
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(ExamTrialDetail.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            // enterExamDateCombo.removeAllItems();
            dtmTrialResult.setRowCount(0);
            ComboItemsAdder.getStudentsOfExam(enterExamDateCombo);
            ComboItemsAdder.getStudentsOfTrial(enterTrialDateCombo);
            ComboItemsAdder.getStudentsOfExamResult(enterExamResultCombo);
            ComboItemsAdder.getStudentsOfTrialResult(enterTrialResultCombo);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ExamTrialDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButton2ActionPerformed

    private void enterTrialResultComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterTrialResultComboActionPerformed
        if (enterTrialResultCombo.getSelectedItem() != null) {
            try {
                alreadyTrialLabel.setVisible(false);
                String nicAndClass = enterTrialResultCombo.getSelectedItem().toString();
                StringTokenizer st = new StringTokenizer(nicAndClass, "_");
                String nic = st.nextToken();
                String classType = st.nextToken();

                Student student = StudentController.searchStudentByNic(nic);
                VehicleClassSet vcs = VehicleClassController.searchVehicleClassSetByName(classType);
                Registration registration = RegistrationController.searchRegistration(student.getStudentId(), vcs.getClassId());
                ridText2.setText(registration.getRegistrationId());
                nameText2.setText(student.getNameWithInitials());
                TrialDetail trialDetail = TrialDetailController.searchLastTrialDetail(registration.getRegistrationId());
                if (trialDetail != null) {
                    attemptText2.setText(Integer.toString(trialDetail.getAttempt()));
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ExamTrialDetail.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_enterTrialResultComboActionPerformed

    private void enterTrialDateComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_enterTrialDateComboItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_enterTrialDateComboItemStateChanged

    private void enterTrialDateComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterTrialDateComboActionPerformed
        if (enterTrialDateCombo.getSelectedItem() != null) {
            try {
                alreadyLabel2.setVisible(false);
                String nicAndClass = enterTrialDateCombo.getSelectedItem().toString();


                StringTokenizer st = new StringTokenizer(nicAndClass, "_");//default delimiter
                String nic = st.nextToken();
                String classType = st.nextToken();

                Student student = StudentController.searchStudentByNic(nic);
                VehicleClassSet vcs = VehicleClassController.searchVehicleClassSetByName(classType);
                Registration registration = RegistrationController.searchRegistration(student.getStudentId(), vcs.getClassId());
                ridText3.setText(registration.getRegistrationId());
                nameText3.setText(student.getNameWithInitials());
                ExamDetail examDetail = ExamDetailController.searchLastExamResult(registration.getRegistrationId());
                if (examDetail != null) {
                    attemptText3.setText(Integer.toString(examDetail.getAttempt() + 1));
                } else {
                    attemptText3.setText(Integer.toString(1));
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(ExamTrialDetail.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_enterTrialDateComboActionPerformed

    private void addTrialDateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTrialDateButtonActionPerformed
        alreadyLabel2.setVisible(false);
        String trialDate = sdf.format(trialDateChooser1.getDate());
        String regID = ridText3.getText();
        String nicAndClass = enterTrialDateCombo.getSelectedItem().toString();
        StringTokenizer st = new StringTokenizer(nicAndClass, "_");//default delimiter
        String nic = st.nextToken();
        String name = nameText3.getText();
        String attempt = attemptText3.getText();
        dtmTrialDate = (DefaultTableModel) trialDateTable.getModel();
        int sameRow = 0;

        if (dtmTrialDate.getRowCount() > 0) {
            for (int i = 0; i < dtmTrialDate.getRowCount(); i++) {
                if (trialDate.equals(dtmTrialDate.getValueAt(i, 0).toString())
                        & regID.equals(dtmTrialDate.getValueAt(i, 1).toString())
                        & nic.equals(dtmTrialDate.getValueAt(i, 2).toString())
                        & name.equals(dtmTrialDate.getValueAt(i, 3).toString())
                        & attempt.equals(dtmTrialDate.getValueAt(i, 4).toString())) {
                    sameRow++;
                }
            }
            if (sameRow == 0) {

                dtmTrialDate.addRow(new Object[]{trialDate, regID, nic, name, attempt});
                enterTrialDateCombo.removeItem(nicAndClass);
                alreadyLabel2.setVisible(false);
            } else {
                alreadyLabel2.setVisible(true);
            }
            sameRow = 0;
        } else if (dtmTrialDate.getRowCount() == 0) {
            dtmTrialDate.addRow(new Object[]{trialDate, regID, nic, name, attempt});
            enterTrialDateCombo.removeItem(nicAndClass);
            alreadyLabel2.setVisible(false);
        }
//         try { //enterExamDateCombo.removeAllItems();
//             ComboItemsAdder.getStudentsOfExam(enterExamDateCombo);
//             System.out.println("sdf");
//        } catch (SQLException | ClassNotFoundException ex) {
//            Logger.getLogger(ExamTrialDetail.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_addTrialDateButtonActionPerformed

    private void saveButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButton3ActionPerformed
       try {
            for (int i = 0; i < dtmTrialDate.getRowCount(); i++) {
                try {
                    TrialDetail trialDetail = new TrialDetail(dtmTrialDate.getValueAt(i, 1).toString(), Integer.parseInt(dtmTrialDate.getValueAt(i, 4).toString()), dtmTrialDate.getValueAt(i, 0).toString());
                    TrialDetailController.addTrialDetail(trialDetail);
                } catch (SQLException | ClassNotFoundException ex) {
                    Logger.getLogger(ExamTrialDetail.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            // enterTrialDateCombo.removeAllItems();
            dtmTrialDate.setRowCount(0);
            ComboItemsAdder.getStudentsOfTrial(enterTrialDateCombo);
            ComboItemsAdder.getStudentsOfTrial(enterTrialDateCombo);
            ComboItemsAdder.getStudentsOfTrialResult(enterTrialResultCombo);
            ComboItemsAdder.getStudentsOfTrialResult(enterTrialResultCombo);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ExamTrialDetail.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButton3ActionPerformed

    private void examDateChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_examDateChooserPropertyChange
        System.out.println("q");
    }//GEN-LAST:event_examDateChooserPropertyChange

    private void trialDateChooser1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_trialDateChooser1KeyReleased
     
    }//GEN-LAST:event_trialDateChooser1KeyReleased

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton addButton1;
    private javax.swing.JButton addTrialButton;
    private javax.swing.JButton addTrialDateButton;
    private javax.swing.JLabel alreadyLabel;
    private javax.swing.JLabel alreadyLabel1;
    private javax.swing.JLabel alreadyLabel2;
    private javax.swing.JLabel alreadyTrialLabel;
    private javax.swing.JTextField attemptText;
    private javax.swing.JTextField attemptText1;
    private javax.swing.JTextField attemptText2;
    private javax.swing.JTextField attemptText3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox enterExamDateCombo;
    private javax.swing.JComboBox enterExamResultCombo;
    private javax.swing.JComboBox enterTrialDateCombo;
    private javax.swing.JComboBox enterTrialResultCombo;
    private com.toedter.calendar.JDateChooser examDateChooser;
    private javax.swing.JTable examDateTable;
    private com.toedter.calendar.JDateChooser examRDateChooser;
    private javax.swing.JTable examResultTable;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitButton1;
    private javax.swing.JButton exitButton2;
    private javax.swing.JButton exitButton3;
    private javax.swing.JRadioButton failedRButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField nameText1;
    private javax.swing.JTextField nameText2;
    private javax.swing.JTextField nameText3;
    private javax.swing.JLabel nicLabel;
    private javax.swing.JLabel nicLabel1;
    private javax.swing.JRadioButton passedRButton;
    private javax.swing.JTextField ridText;
    private javax.swing.JTextField ridText1;
    private javax.swing.JTextField ridText2;
    private javax.swing.JTextField ridText3;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton saveButton1;
    private javax.swing.JButton saveButton2;
    private javax.swing.JButton saveButton3;
    private com.toedter.calendar.JDateChooser trialDateChooser;
    private com.toedter.calendar.JDateChooser trialDateChooser1;
    private javax.swing.JTable trialDateTable;
    private javax.swing.JTable trialResultTable;
    // End of variables declaration//GEN-END:variables
}
