/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dsms.views;

import dsms.common_classes.CalculationMaker;
import dsms.common_classes.ComboItemsAdder;
import dsms.common_classes.ComboSearch;
import dsms.common_classes.ReportConnector;
import dsms.controllers.*;
import dsms.models.*;
import dsms.views.backups.BackUp;
import dsms.views.backups.Restore;
import dsms.views.common_views.InstructorDetailManagerCommon;
import dsms.views.common_views.PaymentOfStudentCommon;
import dsms.views.common_views.StudentDetailManagerCommon;
import dsms.views.common_views.VehicleClassDetailsViewerCommon;
import dsms.views.report_dialogs.InstructorProgress;
import dsms.views.report_dialogs.PaymentReportDialog;
import dsms.views.report_dialogs.RegistrationBasedReportDialog;
import dsms.views.report_dialogs.UpcoimngTriaExamlList;
import dsms.views.user_accounts_handlers.NewUserCreator;
import dsms.views.user_accounts_handlers.PasswordManager;
import dsms.views.user_accounts_handlers.StartLogIn;
import dsms.views.user_accounts_handlers.ViewAllUsers;
import dsms.views.view_utilities.Calculator;
import dsms.views.view_utilities.Calender;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class FrontPage extends javax.swing.JFrame {

    String user;
    LogIn logIn;
    Registration registration;

    /**
     * Creates new form Start1
     */
    public FrontPage(String user) {

        initComponents();
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/dsms/images/logo30.jpg"));
        setIconImage(icon1.getImage());
        this.user = user;
        userNameLabel.setText("" + user + " logged in");
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        try {
            logIn = LogInController.searchUser(user);
            ComboItemsAdder.addAllStudent(studentIDCombo);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(FrontPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        ComboSearch.setSearchableCombo(studentIDCombo, true, "no result!");
        if (logIn.getAbility() == 2) {
            attendanceButton.setEnabled(false);
            resultButton.setEnabled(false);
            addNewUserMenuItem.setEnabled(false);
            restoreMenuItem.setEnabled(false);
        }
        paymentButton.doClick();
//        FlashPanel fp = null;
//        try {
//            fp = new FlashPanel(new File("src/dsms/images/clock102.swf"));
//        } catch (JFlashLibraryLoadFailedException | JFlashInvalidFlashException | FileNotFoundException ex) {
//            Logger.getLogger(StartAny.class.getName()).log(Level.SEVERE, null, ex);
//        }
//       
//        fp.setBackground(clockpanel.getBackground());
//        clockpanel.add(fp);
//        fp.play();

    }

    public FrontPage() {
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/dsms/images/logo30.jpg"));
        setIconImage(icon1.getImage());
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        try {
            ComboItemsAdder.addAllStudent(studentIDCombo);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(FrontPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        ComboSearch.setSearchableCombo(studentIDCombo, true, "no result!");
        paymentButton.doClick();
//
//        FlashPanel fp = null;
//        try {
//            fp = new FlashPanel(new File("src/dsms/images/clock102.swf"));
//        } catch (JFlashLibraryLoadFailedException | JFlashInvalidFlashException | FileNotFoundException ex) {
//            Logger.getLogger(StartAny.class.getName()).log(Level.SEVERE, null, ex);
//        }
//       
//        fp.setBackground(clockpanel.getBackground());
//        clockpanel.add(fp);
//        fp.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        trialResultText = new javax.swing.JTextField();
        examDateText = new javax.swing.JTextField();
        statusText = new javax.swing.JTextField();
        examResultText = new javax.swing.JTextField();
        trialDateText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        vehicleClassText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        instructorText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        noOfDaysText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        totalFeeText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        balanceText = new javax.swing.JTextField();
        studentIDCombo = new javax.swing.JComboBox();
        printButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        userNameLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        registerNewStudentButton = new javax.swing.JButton();
        paymentButton = new javax.swing.JButton();
        attendanceButton = new javax.swing.JButton();
        studentButton = new javax.swing.JButton();
        instructorButton = new javax.swing.JButton();
        resultButton = new javax.swing.JButton();
        courseDetailButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        myAccountMenu = new javax.swing.JMenu();
        changePasswordMenuItem = new javax.swing.JMenuItem();
        addNewUserMenuItem = new javax.swing.JMenuItem();
        viewAllUsersMenuItem = new javax.swing.JMenuItem();
        backUpMenu = new javax.swing.JMenu();
        createBackupMenuItem = new javax.swing.JMenuItem();
        restoreMenuItem = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        instructorProgressMenuItem = new javax.swing.JMenuItem();
        paymentStatsMenuItem = new javax.swing.JMenuItem();
        registrationStatsMenuItem = new javax.swing.JMenuItem();
        trialExamListMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1366, 768));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        desktopPane.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new javax.swing.ImageIcon(getClass().getResource("/dsms/images/front1 (1) - Copy.jpg")))); // NOI18N
        desktopPane.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        desktopPane.setOpaque(false);

        jXPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jXPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(102, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Search:");

        jLabel2.setText("Name:");

        jLabel5.setText("Trial Results:");

        jLabel6.setText("Status:");

        jLabel7.setText("Trial date:");

        jLabel8.setText("Exam Results:");

        jLabel9.setText("Exam date:");

        jLabel10.setText("Vehicle Class:");

        jLabel11.setText("Instructor:");

        jLabel12.setText("No. of days came:");

        jLabel13.setText("out of 15");

        jLabel14.setText("Total fee:");

        jLabel15.setText("Balance to pay:");

        studentIDCombo.setEditable(true);
        studentIDCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDComboActionPerformed(evt);
            }
        });

        printButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Print.png"))); // NOI18N
        printButton.setText("Print Student Report");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentIDCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(trialDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(trialResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(examResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(examDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vehicleClassText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(instructorText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noOfDaysText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalFeeText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(balanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(printButton))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(studentIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(39, 39, 39)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(examDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(examResultText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(trialDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(trialResultText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(vehicleClassText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(instructorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noOfDaysText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(totalFeeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(balanceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(printButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/images/logo80.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/images/Title.png"))); // NOI18N
        jLabel4.setToolTipText("");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(217, 217, 217))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel17))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(64, 64, 64));

        exitButton.setBackground(new java.awt.Color(153, 153, 255));
        exitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitButton.setForeground(new java.awt.Color(0, 0, 204));
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/48x48/Turn off.png"))); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        logOutButton.setBackground(new java.awt.Color(153, 153, 255));
        logOutButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logOutButton.setForeground(new java.awt.Color(0, 0, 204));
        logOutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/48x48/Logout.png"))); // NOI18N
        logOutButton.setText("Log out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        userNameLabel.setFont(new java.awt.Font("Tiranti Solid LET", 1, 24)); // NOI18N
        userNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        userNameLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/user_orange.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(userNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logOutButton)
                    .addComponent(exitButton))
                .addGap(3, 3, 3))
        );

        jPanel5.setLayout(new java.awt.GridLayout(1, 4));

        jButton3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/64x64/Open-Folder-Warning256.png"))); // NOI18N
        jButton3.setToolTipText("Alerts Today");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3);

        jButton2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/64x64/Calendar68.png"))); // NOI18N
        jButton2.setToolTipText("Calender");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2);

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/64x64/calculator.png"))); // NOI18N
        jButton1.setToolTipText("Calculator");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/64x64/event-search64.png"))); // NOI18N
        jButton4.setToolTipText("add new lectures");
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new java.awt.GridLayout(7, 1, 10, 10));

        registerNewStudentButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        registerNewStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/64x64/Child_Male_Light.png"))); // NOI18N
        registerNewStudentButton.setText("1-Student Registration");
        registerNewStudentButton.setBorderPainted(false);
        registerNewStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerNewStudentButtonActionPerformed(evt);
            }
        });
        jPanel2.add(registerNewStudentButton);

        paymentButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        paymentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/64x64/cash_register.png"))); // NOI18N
        paymentButton.setText("2-New Payment           ");
        paymentButton.setBorderPainted(false);
        paymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentButtonActionPerformed(evt);
            }
        });
        jPanel2.add(paymentButton);

        attendanceButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        attendanceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/64x64/add-female-user64.png"))); // NOI18N
        attendanceButton.setText("3-Attendance            ");
        attendanceButton.setBorderPainted(false);
        attendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceButtonActionPerformed(evt);
            }
        });
        jPanel2.add(attendanceButton);

        studentButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        studentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/64x64/personal-information64.png"))); // NOI18N
        studentButton.setText("4-Student Details     ");
        studentButton.setBorderPainted(false);
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButtonActionPerformed(evt);
            }
        });
        jPanel2.add(studentButton);

        instructorButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        instructorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/64x64/Customer_Male_Light.png"))); // NOI18N
        instructorButton.setText("5-Instructors Details   ");
        instructorButton.setBorderPainted(false);
        instructorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorButtonActionPerformed(evt);
            }
        });
        jPanel2.add(instructorButton);

        resultButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resultButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/64x64/Documents3422334.png"))); // NOI18N
        resultButton.setText("6-Exam & Trial Details  ");
        resultButton.setBorderPainted(false);
        resultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultButtonActionPerformed(evt);
            }
        });
        jPanel2.add(resultButton);

        courseDetailButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        courseDetailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/64x64/search vhcl.png"))); // NOI18N
        courseDetailButton.setText("7-Classes & fees details");
        courseDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseDetailButtonActionPerformed(evt);
            }
        });
        jPanel2.add(courseDetailButton);

        myAccountMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        myAccountMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/Community Help.png"))); // NOI18N
        myAccountMenu.setText("My Account");
        myAccountMenu.setBorderPainted(true);
        myAccountMenu.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        changePasswordMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        changePasswordMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/user_edit.png"))); // NOI18N
        changePasswordMenuItem.setText("Change Password");
        changePasswordMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordMenuItemActionPerformed(evt);
            }
        });
        myAccountMenu.add(changePasswordMenuItem);

        addNewUserMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addNewUserMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/user_add.png"))); // NOI18N
        addNewUserMenuItem.setText("Add new user");
        addNewUserMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewUserMenuItemActionPerformed(evt);
            }
        });
        myAccountMenu.add(addNewUserMenuItem);

        viewAllUsersMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewAllUsersMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/group.png"))); // NOI18N
        viewAllUsersMenuItem.setText("View All users");
        viewAllUsersMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllUsersMenuItemActionPerformed(evt);
            }
        });
        myAccountMenu.add(viewAllUsersMenuItem);

        jMenuBar1.add(myAccountMenu);

        backUpMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        backUpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/DOC FOLDER.png"))); // NOI18N
        backUpMenu.setText("BackUp");
        backUpMenu.setBorderPainted(true);
        backUpMenu.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        createBackupMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        createBackupMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/database_save.png"))); // NOI18N
        createBackupMenuItem.setText("Create a back-up");
        createBackupMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBackupMenuItemActionPerformed(evt);
            }
        });
        backUpMenu.add(createBackupMenuItem);

        restoreMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        restoreMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/database_refresh.png"))); // NOI18N
        restoreMenuItem.setText("Restore using a backup");
        restoreMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restoreMenuItemActionPerformed(evt);
            }
        });
        backUpMenu.add(restoreMenuItem);

        jMenuBar1.add(backUpMenu);

        jMenu1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/Stocks.png"))); // NOI18N
        jMenu1.setText(" Statistics & Reports");
        jMenu1.setBorderPainted(true);
        jMenu1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N

        instructorProgressMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        instructorProgressMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/user folder.png"))); // NOI18N
        instructorProgressMenuItem.setText("Instructor Progress Reports");
        instructorProgressMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorProgressMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(instructorProgressMenuItem);

        paymentStatsMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        paymentStatsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/earning-statements32.png"))); // NOI18N
        paymentStatsMenuItem.setText("Payment Statistics");
        paymentStatsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentStatsMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(paymentStatsMenuItem);

        registrationStatsMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registrationStatsMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/Documents8686.png"))); // NOI18N
        registrationStatsMenuItem.setText("Registration Statistics");
        registrationStatsMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrationStatsMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(registrationStatsMenuItem);

        trialExamListMenuItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        trialExamListMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/event-search32.png"))); // NOI18N
        trialExamListMenuItem.setText("Trial & Exam Lists");
        trialExamListMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trialExamListMenuItemActionPerformed(evt);
            }
        });
        jMenu1.add(trialExamListMenuItem);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(desktopPane)))
                .addGap(18, 18, 18)
                .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 104, Short.MAX_VALUE))
                            .addComponent(desktopPane)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerNewStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerNewStudentButtonActionPerformed

        desktopPane.removeAll();
        StudentRegistration sg = new StudentRegistration();
        sg.setSize(desktopPane.getSize());
        desktopPane.add(sg);
        sg.setVisible(true);
        sg.requestFocusForm();
    }//GEN-LAST:event_registerNewStudentButtonActionPerformed

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        desktopPane.removeAll();
        if (logIn.getAbility() == 1) {
            PaymentOfStudent paymentOfStudent = new PaymentOfStudent(FrontPage.this);
            paymentOfStudent.setSize(desktopPane.getSize());
            desktopPane.add(paymentOfStudent);
            paymentOfStudent.setVisible(true);
            paymentOfStudent.requestFocusForm();
        } else if (logIn.getAbility() == 2) {
            PaymentOfStudentCommon paymentOfStudent = new PaymentOfStudentCommon(FrontPage.this);
            paymentOfStudent.setSize(desktopPane.getSize());
            desktopPane.add(paymentOfStudent);
            paymentOfStudent.setVisible(true);
            paymentOfStudent.requestFocusForm();
        }
    }//GEN-LAST:event_paymentButtonActionPerformed

    private void attendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceButtonActionPerformed
        if (logIn.getAbility() == 1) {
            desktopPane.removeAll();
            StudentAttendanceI studentAttendanceI = new StudentAttendanceI();
            studentAttendanceI.setSize(desktopPane.getSize());
            desktopPane.add(studentAttendanceI);
            studentAttendanceI.setVisible(true);
            studentAttendanceI.requestFocusForm();
        }
    }//GEN-LAST:event_attendanceButtonActionPerformed

    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
        desktopPane.removeAll();
        if (logIn.getAbility() == 1) {
            StudentDetailManager studentDetailManager = new StudentDetailManager();
            studentDetailManager.setSize(desktopPane.getSize());
            desktopPane.add(studentDetailManager);
            studentDetailManager.setVisible(true);
            studentDetailManager.requestFocusForm();
            studentDetailManager.requestFocusForm();
        } else if (logIn.getAbility() == 2) {
            StudentDetailManagerCommon studentDetailManager = new StudentDetailManagerCommon();
            studentDetailManager.setSize(desktopPane.getSize());
            desktopPane.add(studentDetailManager);
            studentDetailManager.setVisible(true);
            studentDetailManager.requestFocusForm();
        }

    }//GEN-LAST:event_studentButtonActionPerformed

    private void courseDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseDetailButtonActionPerformed
        desktopPane.removeAll();
        if (logIn.getAbility() == 1) {
            VehicleClassDetailsViewer detailsViewer = new VehicleClassDetailsViewer();
            detailsViewer.setSize(desktopPane.getSize());
            desktopPane.add(detailsViewer);
            detailsViewer.setVisible(true);
            //        detailsViewer.requestFocusForm();
        } else if (logIn.getAbility() == 2) {
            VehicleClassDetailsViewerCommon detailsViewer = new VehicleClassDetailsViewerCommon();
            detailsViewer.setSize(desktopPane.getSize());
            desktopPane.add(detailsViewer);
            detailsViewer.setVisible(true);
            //    detailsViewer.requestFocusForm();
        }
    }//GEN-LAST:event_courseDetailButtonActionPerformed

    private void resultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultButtonActionPerformed
        if (logIn.getAbility() == 1) {
            desktopPane.removeAll();
            ExamTrialDetail examTrialDetail = new ExamTrialDetail();
            examTrialDetail.setSize(desktopPane.getSize());
            desktopPane.add(examTrialDetail);
            examTrialDetail.setVisible(true);
            examTrialDetail.requestFocusForm();
        }
    }//GEN-LAST:event_resultButtonActionPerformed

    private void instructorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorButtonActionPerformed
        desktopPane.removeAll();
        if (logIn.getAbility() == 1) {
            InstructorDetailManager instructorDetailManager = new InstructorDetailManager();
            instructorDetailManager.setSize(desktopPane.getSize());
            instructorDetailManager.setVisible(true);
            desktopPane.add(instructorDetailManager);
            instructorDetailManager.requestFocusForm();
        } else if (logIn.getAbility() == 2) {
            InstructorDetailManagerCommon instructorDetailManager = new InstructorDetailManagerCommon();
            instructorDetailManager.setSize(desktopPane.getSize());
            instructorDetailManager.setVisible(true);
            desktopPane.add(instructorDetailManager);
            instructorDetailManager.requestFocusForm();
        }
    }//GEN-LAST:event_instructorButtonActionPerformed

    private void studentIDComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDComboActionPerformed
        try {
            if (studentIDCombo.getSelectedItem() != null) {
                String nameAndSid = studentIDCombo.getSelectedItem().toString();
                StringTokenizer stringTokenizer = new StringTokenizer(nameAndSid, "_");
                if (stringTokenizer.countTokens() == 2) {
                    String name = stringTokenizer.nextToken();
                    String studentId = stringTokenizer.nextToken();
                    Student student = StudentController.searchStudent(studentId);
                    nameText.setText(student.getNameWithInitials());

                    registration = RegistrationController.searchLastRegistration(studentId);
                    int status = registration.getStatus();
                    if (status == 1) {
                        statusText.setText("Training");
                    } else if (status == 0) {
                        statusText.setText("Finished");
                    }
                    VehicleClassSet classSet = VehicleClassController.searchVehicleClassSet(registration.getClassId());
                    vehicleClassText.setText(classSet.getClassType());
                    Instructor instructor = InstructorController.searchInstructor(registration.getInstructorId());
                    instructorText.setText(instructor.getName());
                    int noOfDays = 0;
                    noOfDays = StudentAttendanceController.getAttendanceCount(registration);
                    noOfDaysText.setText(Integer.toString(noOfDays));
                    totalFeeText.setText(Double.toString(registration.getTotalFee()));
                    double paidTotal = CalculationMaker.paymentsAdder(registration.getRegistrationId());
                    balanceText.setText(Double.toString(registration.getTotalFee() - paidTotal));
                    ExamDetail examDetail = ExamDetailController.searchLastExamResult(registration.getRegistrationId());
                    if (examDetail != null) {
                        examDateText.setText(examDetail.getDate());
                        if (examDetail.getResult() == 0) {
                            examResultText.setText("Not paiticipated");
                        } else if (examDetail.getResult() == 1) {
                            examResultText.setText("Passed");
                        } else if (examDetail.getResult() == -1) {
                            examResultText.setText("Failed");
                        }

                    } else {
                        examDateText.setText("Not yet");
                        examResultText.setText("Not yet");
                    }
                    TrialDetail trialDetail = TrialDetailController.searchLastTrialResult(registration.getRegistrationId());
                    if (trialDetail != null) {
                        trialDateText.setText(trialDetail.getDate());
                        if (trialDetail.getResult() == 0) {
                            trialResultText.setText("Not paiticipated");
                        } else if (trialDetail.getResult() == 1) {
                            trialResultText.setText("Passed");
                        } else if (trialDetail.getResult() == -1) {
                            trialResultText.setText("Failed");
                        }

                    } else {
                        trialDateText.setText("Not yet");
                        trialResultText.setText("Not yet");
                    }
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(FrontPage.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_studentIDComboActionPerformed

    private void changePasswordMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordMenuItemActionPerformed
        PasswordManager passwordManager = new PasswordManager(this, true, user);
        passwordManager.setVisible(true);
    }//GEN-LAST:event_changePasswordMenuItemActionPerformed

    private void addNewUserMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewUserMenuItemActionPerformed
        if (logIn.getAbility() == 1) {
            NewUserCreator newUserCreator = new NewUserCreator(this, true);
            newUserCreator.setVisible(true);
        }
    }//GEN-LAST:event_addNewUserMenuItemActionPerformed

    private void viewAllUsersMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllUsersMenuItemActionPerformed
        ViewAllUsers viewAllUsers = new ViewAllUsers(this, true);
        viewAllUsers.setVisible(true);
    }//GEN-LAST:event_viewAllUsersMenuItemActionPerformed

    private void createBackupMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBackupMenuItemActionPerformed
        BackUp backUp = new BackUp(this, true);
        backUp.setVisible(true);
    }//GEN-LAST:event_createBackupMenuItemActionPerformed

    private void restoreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restoreMenuItemActionPerformed
        if (logIn.getAbility() == 1) {
            Restore restore = new Restore(this, true);
            restore.setVisible(true);
        }
    }//GEN-LAST:event_restoreMenuItemActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        int res = JOptionPane.showConfirmDialog(null, "Do you want to log-out now?");
        if (res == 0) {
            StartLogIn startLogIn = new StartLogIn();
            startLogIn.setVisible(true);
            this.dispose();
        }

    }//GEN-LAST:event_logOutButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void instructorProgressMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorProgressMenuItemActionPerformed
        InstructorProgress instructorProgress = new InstructorProgress(this, true);
        instructorProgress.setVisible(true);
    }//GEN-LAST:event_instructorProgressMenuItemActionPerformed

    private void paymentStatsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentStatsMenuItemActionPerformed
        PaymentReportDialog paymentReportDialog = new PaymentReportDialog(this, true);
        paymentReportDialog.setVisible(true);
    }//GEN-LAST:event_paymentStatsMenuItemActionPerformed

    private void registrationStatsMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrationStatsMenuItemActionPerformed
        RegistrationBasedReportDialog rbrd = new RegistrationBasedReportDialog(this, true);
        rbrd.setVisible(true);
    }//GEN-LAST:event_registrationStatsMenuItemActionPerformed

    private void trialExamListMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trialExamListMenuItemActionPerformed
        UpcoimngTriaExamlList upcoimngTriaExamlList = new UpcoimngTriaExamlList(this, true);
        upcoimngTriaExamlList.setVisible(true);
    }//GEN-LAST:event_trialExamListMenuItemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Calculator calculator = new Calculator();
        calculator.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Calender calender = new Calender(this, true, this.jButton2);
        calender.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_1) {
            registerNewStudentButton.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_2) {
            paymentButton.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_3) {
            attendanceButton.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_4) {
            studentButton.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_5) {
            instructorButton.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_6) {
            resultButton.doClick();
        } else if (evt.getKeyCode() == KeyEvent.VK_7) {
            courseDetailButton.doClick();
        }
    }//GEN-LAST:event_formKeyReleased

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try {
            if (studentIDCombo.getSelectedItem() != null) {
                String nameAndSid = studentIDCombo.getSelectedItem().toString();
                StringTokenizer stringTokenizer = new StringTokenizer(nameAndSid, "_");
                if (stringTokenizer.countTokens() == 2) {
                    String name = stringTokenizer.nextToken();
                    String studentId = stringTokenizer.nextToken();
                    Student student = StudentController.searchStudent(studentId);
                    nameText.setText(student.getNameWithInitials());

                    registration = RegistrationController.searchLastRegistration(studentId);
                }
            }
            InputStream inputStream = getClass().getResourceAsStream("/dsms/reports/student_detail_reports/studentRegistrationDetailReport.jrxml");
            HashMap map = new HashMap();
            map.put("registration_id", registration.getRegistrationId());
            System.out.println(registration.getRegistrationId());
            JasperViewer jv = ReportConnector.sendHashMapAndConn(inputStream, map);
            ReportConnector.viewInDialog(jv);
        } catch (ClassNotFoundException | SQLException | JRException ex) {
            Logger.getLogger(RegistrationBasedReportDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_printButtonActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        LectureAdder lectureAdder = new LectureAdder(this, true);
        lectureAdder.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Alerts alerts = new Alerts(this, true);
        alerts.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrontPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new FrontPage().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addNewUserMenuItem;
    private javax.swing.JButton attendanceButton;
    private javax.swing.JMenu backUpMenu;
    private javax.swing.JTextField balanceText;
    private javax.swing.JMenuItem changePasswordMenuItem;
    private javax.swing.JButton courseDetailButton;
    private javax.swing.JMenuItem createBackupMenuItem;
    public javax.swing.JDesktopPane desktopPane;
    private javax.swing.JTextField examDateText;
    private javax.swing.JTextField examResultText;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton instructorButton;
    private javax.swing.JMenuItem instructorProgressMenuItem;
    private javax.swing.JTextField instructorText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JMenu myAccountMenu;
    private javax.swing.JTextField nameText;
    private javax.swing.JTextField noOfDaysText;
    private javax.swing.JButton paymentButton;
    private javax.swing.JMenuItem paymentStatsMenuItem;
    private javax.swing.JButton printButton;
    public javax.swing.JButton registerNewStudentButton;
    private javax.swing.JMenuItem registrationStatsMenuItem;
    private javax.swing.JMenuItem restoreMenuItem;
    private javax.swing.JButton resultButton;
    private javax.swing.JTextField statusText;
    private javax.swing.JButton studentButton;
    private javax.swing.JComboBox studentIDCombo;
    private javax.swing.JTextField totalFeeText;
    private javax.swing.JTextField trialDateText;
    private javax.swing.JMenuItem trialExamListMenuItem;
    private javax.swing.JTextField trialResultText;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField vehicleClassText;
    private javax.swing.JMenuItem viewAllUsersMenuItem;
    // End of variables declaration//GEN-END:variables
}
