/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dsms.views;

import dsms.common_classes.CalculationMaker;
import dsms.common_classes.ComboItemsAdder;
import dsms.common_classes.ComboSearch;
import dsms.controllers.CodeGenerateController;
import dsms.controllers.InstructorAttendanceController;
import dsms.controllers.InstructorController;
import dsms.controllers.VehicleClassController;
import dsms.models.Instructor;
import dsms.models.InstructorAttendance;
import dsms.models.VehicleClassSet;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class InstructorDetailManager extends javax.swing.JInternalFrame {

    String instructorId;
    String instructorName;
    String timeIn;
    String timeOut;
    DefaultTableModel dtm;

    public InstructorDetailManager() {

        initComponents();
        setTitle("Instructor Details");
        
        //////////////////register////////////////////////////////////
        try {
            CodeGenerateController.getNextID(iidTextR, "I", "instructorId", "Instructor");
            dateChooser.setDate(new Date());
            ComboItemsAdder.addAllVehicleClass(classComboBox1);
            nameWithInitialsTextR.requestFocus();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(InstructorDetailManager.class.getName()).log(Level.SEVERE, null, ex);
        }
        ////////////////////update//////////////////////////////////////
        try {
            ComboItemsAdder.addAllInstructors(instructorComboBox);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(InstructorDetailManager.class.getName()).log(Level.SEVERE, null, ex);
        }
        ComboSearch.searchCombo(instructorComboBox, "Instructor", "name");
        nameEditText.requestFocus();

        ////////////////////markAttendance///////////////////////////////////
        dateChooserM.setDate(new Date());
        try {
            ComboItemsAdder.addAllInstructors(instructorComboBoxA);
            inHourSpinner.setValue(1);
            outHourSpinner.setValue(1);
            inMinuteSpinner.setValue(00);
            outMinuteSpinner.setValue(00);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(InstructorDetailManager.class.getName()).log(Level.SEVERE, null, ex);
        }
        ComboSearch.searchCombo(instructorComboBoxA, "Instructor", "instructorId");
    }
public void requestFocusForm(){
    instructorComboBox.requestFocus();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        updateInstructorPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        nameText = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        telLabel = new javax.swing.JLabel();
        telephoneText = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        nicLabel = new javax.swing.JLabel();
        nicText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        nameEditLabel = new javax.swing.JLabel();
        nameEditText = new javax.swing.JTextField();
        classLabel = new javax.swing.JLabel();
        classText = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        driLicNoText = new javax.swing.JTextField();
        dlExpireDateText = new javax.swing.JTextField();
        teachLicNoLabel = new javax.swing.JLabel();
        teachDriLicNoText = new javax.swing.JTextField();
        tdlExpireDateLabel = new javax.swing.JLabel();
        tdlExpireDateText = new javax.swing.JTextField();
        dlExpireDateLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        instructorComboBox = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        updateButton = new javax.swing.JToggleButton();
        deleteButton = new javax.swing.JToggleButton();
        exitButton = new javax.swing.JButton();
        dateText = new javax.swing.JTextField();
        registerNewInstructor = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        iidTextR = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        nameWithInitialsLabel1 = new javax.swing.JLabel();
        nameWithInitialsTextR = new javax.swing.JTextField();
        telLabel1 = new javax.swing.JLabel();
        telephoneTextR = new javax.swing.JTextField();
        addressLabel1 = new javax.swing.JLabel();
        nicLabel1 = new javax.swing.JLabel();
        nicTextR = new javax.swing.JTextField();
        addressTextR = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        classLabel2 = new javax.swing.JLabel();
        classComboBox1 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        driLicNoTextR = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        teachDriLicNoTextR = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        tdlExpireDateChooser = new com.toedter.calendar.JDateChooser();
        dlExpireDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        dateChooser = new com.toedter.calendar.JDateChooser();
        jPanel9 = new javax.swing.JPanel();
        saveButton = new javax.swing.JToggleButton();
        exitButtonR = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        dateChooserM = new com.toedter.calendar.JDateChooser();
        jPanel13 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        instructorComboBoxA = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        inHourSpinner = new javax.swing.JSpinner();
        inMinuteSpinner = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        outHourSpinner = new javax.swing.JSpinner();
        outMinuteSpinner = new javax.swing.JSpinner();
        inAmPm = new javax.swing.JSpinner();
        outAmPm = new javax.swing.JSpinner();
        insNameText = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAttendance = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        saveAButton = new javax.swing.JButton();
        exitAButton = new javax.swing.JButton();

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        updateInstructorPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nameText.setText("Instructor Name  :");

        jLabel5.setText("Date of Registration :");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Detaills"));

        telLabel.setText("Telephone:");

        telephoneText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telephoneTextKeyPressed(evt);
            }
        });

        addressLabel.setText("Address:");

        nicLabel.setText("NIC no:");

        nicText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nicTextKeyPressed(evt);
            }
        });

        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });
        addressText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressTextKeyPressed(evt);
            }
        });

        nameEditLabel.setText("Name:");

        nameEditText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameEditTextKeyPressed(evt);
            }
        });

        classLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        classLabel.setText("Vehicle classes");

        classText.setEditable(false);
        classText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                classTextKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telLabel)
                            .addComponent(addressLabel)
                            .addComponent(nicLabel))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nicText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telephoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(nameEditLabel)
                        .addGap(62, 62, 62)
                        .addComponent(nameEditText, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(classLabel)
                        .addGap(18, 18, 18)
                        .addComponent(classText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameEditLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telLabel)
                    .addComponent(telephoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nicLabel)
                    .addComponent(nicText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("License Details"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Driving License No:");

        driLicNoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                driLicNoTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                driLicNoTextKeyReleased(evt);
            }
        });

        dlExpireDateText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dlExpireDateTextKeyPressed(evt);
            }
        });

        teachLicNoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        teachLicNoLabel.setText("Teaching License No:");

        teachDriLicNoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teachDriLicNoTextKeyPressed(evt);
            }
        });

        tdlExpireDateLabel.setText("TDL Expire date:");

        tdlExpireDateText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tdlExpireDateTextKeyPressed(evt);
            }
        });

        dlExpireDateLabel.setText("DL Expire date:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/contact256.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dlExpireDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(driLicNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dlExpireDateLabel)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teachLicNoLabel)
                            .addComponent(tdlExpireDateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tdlExpireDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teachDriLicNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(driLicNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlExpireDateLabel)
                            .addComponent(dlExpireDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teachLicNoLabel)
                            .addComponent(teachDriLicNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tdlExpireDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tdlExpireDateLabel)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        instructorComboBox.setEditable(true);
        instructorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorComboBoxActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        updateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Update.png"))); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        jPanel8.add(updateButton);

        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        deleteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Erase.png"))); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        jPanel8.add(deleteButton);

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Cancel.png"))); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel8.add(exitButton);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(nameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(instructorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText)
                    .addComponent(jLabel5)
                    .addComponent(instructorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout updateInstructorPanelLayout = new javax.swing.GroupLayout(updateInstructorPanel);
        updateInstructorPanel.setLayout(updateInstructorPanelLayout);
        updateInstructorPanelLayout.setHorizontalGroup(
            updateInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateInstructorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        updateInstructorPanelLayout.setVerticalGroup(
            updateInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateInstructorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update instructor details", new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/user_edit.png")), updateInstructorPanel); // NOI18N

        registerNewInstructor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Instructor ID  :");

        iidTextR.setEditable(false);
        iidTextR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iidTextRActionPerformed(evt);
            }
        });

        jLabel8.setText("Date :");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Detaills"));

        nameWithInitialsLabel1.setText("Name with initials:");

        nameWithInitialsTextR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameWithInitialsTextRKeyPressed(evt);
            }
        });

        telLabel1.setText("Telephone:");

        telephoneTextR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telephoneTextRKeyPressed(evt);
            }
        });

        addressLabel1.setText("Address:");

        nicLabel1.setText("NIC no:");

        nicTextR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nicTextRKeyPressed(evt);
            }
        });

        addressTextR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextRActionPerformed(evt);
            }
        });
        addressTextR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressTextRKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressLabel1)
                            .addComponent(nicLabel1))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nicTextR, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addressTextR, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameWithInitialsLabel1)
                            .addComponent(telLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telephoneTextR, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameWithInitialsTextR, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameWithInitialsTextR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameWithInitialsLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telLabel1)
                    .addComponent(telephoneTextR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel1)
                    .addComponent(addressTextR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nicLabel1)
                    .addComponent(nicTextR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("License Details"));

        classLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        classLabel2.setText("Vehicle classes");

        classComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                classComboBox1KeyPressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel19.setText("Driving License No:");

        driLicNoTextR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                driLicNoTextRKeyPressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel21.setText("Teaching License No:");

        teachDriLicNoTextR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teachDriLicNoTextRKeyPressed(evt);
            }
        });

        jLabel22.setText("TDL Expire date:");

        jLabel24.setText("DL Expire date:");

        tdlExpireDateChooser.setDateFormatString("yyyy-MM-dd");
        tdlExpireDateChooser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tdlExpireDateChooserKeyReleased(evt);
            }
        });

        dlExpireDateChooser.setDateFormatString("yyyy-MM-dd");
        dlExpireDateChooser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dlExpireDateChooserKeyReleased(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/contact256.png"))); // NOI18N

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(jLabel21)
                    .addComponent(classLabel2)
                    .addComponent(jLabel24)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dlExpireDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                    .addComponent(tdlExpireDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(teachDriLicNoTextR)
                    .addComponent(driLicNoTextR)
                    .addComponent(classComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(30, 30, 30))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(driLicNoTextR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(dlExpireDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(teachDriLicNoTextR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel22)
                    .addComponent(tdlExpireDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classLabel2)
                    .addComponent(classComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 139, Short.MAX_VALUE))
        );

        dateChooser.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(iidTextR, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(iidTextR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel8))
                    .addComponent(dateChooser, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Save.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel9.add(saveButton);

        exitButtonR.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exitButtonR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Cancel.png"))); // NOI18N
        exitButtonR.setText("Exit");
        exitButtonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonRActionPerformed(evt);
            }
        });
        jPanel9.add(exitButtonR);

        javax.swing.GroupLayout registerNewInstructorLayout = new javax.swing.GroupLayout(registerNewInstructor);
        registerNewInstructor.setLayout(registerNewInstructorLayout);
        registerNewInstructorLayout.setHorizontalGroup(
            registerNewInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerNewInstructorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(registerNewInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        registerNewInstructorLayout.setVerticalGroup(
            registerNewInstructorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(registerNewInstructorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Register new Instructor", new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/reseller_account.png")), registerNewInstructor); // NOI18N

        jPanel10.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel13.setText("Date:");

        dateChooserM.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateChooserM, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooserM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setText("Instructor:");

        instructorComboBoxA.setEditable(true);
        instructorComboBoxA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorComboBoxAActionPerformed(evt);
            }
        });

        jLabel15.setText("Time in:");

        jLabel16.setText("Time out:");

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Plus.png"))); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        inHourSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        inHourSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                inHourSpinnerStateChanged(evt);
            }
        });
        inHourSpinner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inHourSpinnerKeyReleased(evt);
            }
        });

        inMinuteSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 5));
        inMinuteSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                inMinuteSpinnerStateChanged(evt);
            }
        });
        inMinuteSpinner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                inMinuteSpinnerKeyReleased(evt);
            }
        });

        jLabel2.setText(":");

        jLabel3.setText(":");

        outHourSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        outHourSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                outHourSpinnerStateChanged(evt);
            }
        });
        outHourSpinner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                outHourSpinnerKeyReleased(evt);
            }
        });

        outMinuteSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 59, 5));
        outMinuteSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                outMinuteSpinnerStateChanged(evt);
            }
        });
        outMinuteSpinner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                outMinuteSpinnerKeyReleased(evt);
            }
        });

        inAmPm.setModel(new javax.swing.SpinnerListModel(new String[] {"AM", "PM"}));

        outAmPm.setModel(new javax.swing.SpinnerListModel(new String[] {"PM", "AM"}));
        outAmPm.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                outAmPmStateChanged(evt);
            }
        });
        outAmPm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                outAmPmKeyReleased(evt);
            }
        });

        insNameText.setEditable(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(inHourSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inMinuteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(instructorComboBoxA, 0, 1, Short.MAX_VALUE))
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inAmPm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outHourSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(outMinuteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(outAmPm, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(insNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(instructorComboBoxA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(insNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(outHourSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(outMinuteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(outAmPm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16)
                        .addComponent(inHourSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(inMinuteSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(inAmPm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(addButton)
                .addContainerGap())
        );

        tableAttendance.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Instructor Id", "Instructor", "Time in", "Time out"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAttendance.getTableHeader().setReorderingAllowed(false);
        tableAttendance.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tableAttendanceKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tableAttendance);
        tableAttendance.getColumnModel().getColumn(0).setPreferredWidth(10);
        tableAttendance.getColumnModel().getColumn(2).setPreferredWidth(10);
        tableAttendance.getColumnModel().getColumn(3).setPreferredWidth(10);

        jPanel12.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        saveAButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveAButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Save.png"))); // NOI18N
        saveAButton.setText("SAVE");
        saveAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAButtonActionPerformed(evt);
            }
        });
        jPanel12.add(saveAButton);

        exitAButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exitAButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Cancel.png"))); // NOI18N
        exitAButton.setText("EXIT");
        exitAButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitAButtonActionPerformed(evt);
            }
        });
        jPanel12.add(exitAButton);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 645, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mark instructor attendance", new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/wishlist_add.png")), jPanel1); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telephoneTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telephoneTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addressText.requestFocus();
        }
    }//GEN-LAST:event_telephoneTextKeyPressed

    private void nicTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            driLicNoText.requestFocus();
        }
    }//GEN-LAST:event_nicTextKeyPressed

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
    }//GEN-LAST:event_addressTextActionPerformed

    private void addressTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            nicText.requestFocus();
        }
    }//GEN-LAST:event_addressTextKeyPressed

    private void nameWithInitialsTextRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameWithInitialsTextRKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            telephoneTextR.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            telephoneTextR.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            dateChooser.requestFocus();
        }
    }//GEN-LAST:event_nameWithInitialsTextRKeyPressed

    private void telephoneTextRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telephoneTextRKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addressTextR.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            addressTextR.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            nameWithInitialsTextR.requestFocus();
        }
    }//GEN-LAST:event_telephoneTextRKeyPressed

    private void nicTextRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicTextRKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            driLicNoTextR.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            driLicNoTextR.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            addressTextR.requestFocus();
        }
    }//GEN-LAST:event_nicTextRKeyPressed

    private void addressTextRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextRActionPerformed
    }//GEN-LAST:event_addressTextRActionPerformed

    private void addressTextRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTextRKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            nicTextR.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            nicTextR.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            telephoneTextR.requestFocus();
        }
    }//GEN-LAST:event_addressTextRKeyPressed

    private void iidTextRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iidTextRActionPerformed
    }//GEN-LAST:event_iidTextRActionPerformed

    private void instructorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorComboBoxActionPerformed
        addInstructorData();
    }//GEN-LAST:event_instructorComboBoxActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
           String  instructorSel = instructorComboBox.getSelectedItem().toString();
           StringTokenizer st=new StringTokenizer(instructorSel, "_");          
          String name=st.nextToken();
          instructorId=st.nextToken();
            Instructor instructor = InstructorController.searchInstructor(instructorId);
            instructor.setName(nameEditText.getText());
            instructor.setAddress(addressText.getText());
            instructor.setInstructorTel(telephoneText.getText());
            instructor.setNic(nicText.getText());
            instructor.setDateOfRegistration(dateText.getText());
            instructor.setDriverLicenceNo(driLicNoText.getText());
            instructor.setDriverLicenceExpireDate(dlExpireDateText.getText());
            instructor.setTeachingLicenceNo(teachDriLicNoText.getText());
            instructor.setTeachingLicenceExpireDate(tdlExpireDateText.getText());
            //Instructor instructor = getDataFromForm(instructorId);
            int res = InstructorController.updateInstructor(instructor);
            if (res > 0) {
                JOptionPane.showMessageDialog(InstructorDetailManager.this, "Updated!");
            } else {
                JOptionPane.showMessageDialog(InstructorDetailManager.this, "Failed!");
            }
            ComboItemsAdder.addAllInstructors(instructorComboBox);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(InstructorDetailManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
             String  instructorSel = instructorComboBox.getSelectedItem().toString();
           StringTokenizer st=new StringTokenizer(instructorSel, "_");          
          String name=st.nextToken();
          instructorId=st.nextToken();
          
           
            int result = InstructorController.deleteInstructor(instructorId);
            if (result > 0) {
                JOptionPane.showMessageDialog(InstructorDetailManager.this, "Deleted!");
            } else {
                JOptionPane.showMessageDialog(InstructorDetailManager.this, "Failed!");
            }
            ComboItemsAdder.addAllInstructors(instructorComboBox);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(InstructorDetailManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void nameEditTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameEditTextKeyPressed
    }//GEN-LAST:event_nameEditTextKeyPressed

    private void classTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classTextKeyPressed
    }//GEN-LAST:event_classTextKeyPressed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            Instructor instructor = new Instructor();
            instructor.setInstructorId(iidTextR.getText());
            instructor.setName(nameWithInitialsTextR.getText());
            instructor.setAddress(addressTextR.getText());
            instructor.setInstructorTel(telephoneTextR.getText());
            instructor.setNic(nicTextR.getText());
            Date date = dateChooser.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            instructor.setDateOfRegistration(sdf.format(date));
            instructor.setDriverLicenceNo(driLicNoTextR.getText());
            if (dlExpireDateChooser.getDate() != null) {
                Date dateExp = dlExpireDateChooser.getDate();
                instructor.setDriverLicenceExpireDate(sdf.format(dateExp));
            }
            instructor.setTeachingLicenceNo(teachDriLicNoTextR.getText());
            if (tdlExpireDateChooser.getDate() != null) {
                Date dateTDl = tdlExpireDateChooser.getDate();
                instructor.setTeachingLicenceExpireDate(sdf.format(dateTDl));
            }
            VehicleClassSet vehicleClassSet = VehicleClassController.searchVehicleClassSetByName(classComboBox1.getSelectedItem().toString());
            instructor.setClassId(vehicleClassSet.getClassId());
            //  Instructor instructor = getDataFromForm(iidTextR.getText());
            int res = InstructorController.addNewInstructor(instructor);
            if (res > 0) {
                JOptionPane.showMessageDialog(InstructorDetailManager.this, "Registration successful!");
            } else {
                JOptionPane.showMessageDialog(InstructorDetailManager.this, "Failed!");
            }
            ComboItemsAdder.addAllInstructors(instructorComboBox);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(InstructorDetailManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void exitButtonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonRActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonRActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        addRowToTable();
    }//GEN-LAST:event_addButtonActionPerformed

    private void saveAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAButtonActionPerformed
        dtm = (DefaultTableModel) tableAttendance.getModel();
        ArrayList<InstructorAttendance> attendanceSet = new ArrayList<>();
        Date dateM = dateChooserM.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String date = sdf.format(dateM);
        try {
            for (int i = 0; i < dtm.getRowCount(); i++) {
                Instructor instructor = InstructorController.searchInstructorByName(dtm.getValueAt(i, 0).toString());
                if (instructor != null) {
                    InstructorAttendance instructorAttendance = new InstructorAttendance(instructor.getInstructorId(), date, dtm.getValueAt(i, 2).toString(), dtm.getValueAt(i, 3).toString());
                    attendanceSet.add(instructorAttendance);
                }

            }
            int res = InstructorAttendanceController.addInstructorAttendance(attendanceSet);
            if (res > 0) {
                JOptionPane.showMessageDialog(InstructorDetailManager.this, "Saved!");
            } else {
                JOptionPane.showMessageDialog(InstructorDetailManager.this, "Failed!");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(InstructorDetailManager.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_saveAButtonActionPerformed

    private void driLicNoTextRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_driLicNoTextRKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            dlExpireDateChooser.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            dlExpireDateChooser.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            nicTextR.requestFocus();
        }
    }//GEN-LAST:event_driLicNoTextRKeyPressed

    private void dlExpireDateChooserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dlExpireDateChooserKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            teachDriLicNoTextR.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            teachDriLicNoTextR.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            driLicNoTextR.requestFocus();
        }
    }//GEN-LAST:event_dlExpireDateChooserKeyReleased

    private void teachDriLicNoTextRKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teachDriLicNoTextRKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            tdlExpireDateChooser.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tdlExpireDateChooser.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            driLicNoTextR.requestFocus();
        }
    }//GEN-LAST:event_teachDriLicNoTextRKeyPressed

    private void tdlExpireDateChooserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tdlExpireDateChooserKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            classComboBox1.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
            classComboBox1.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            teachDriLicNoTextR.requestFocus();
        }
    }//GEN-LAST:event_tdlExpireDateChooserKeyReleased

    private void classComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classComboBox1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            //  saveButton.doClick();
        }
    }//GEN-LAST:event_classComboBox1KeyPressed

    private void inHourSpinnerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inHourSpinnerKeyReleased
        CalculationMaker.limitSpinnerValue(inHourSpinner, 1, 12);
    }//GEN-LAST:event_inHourSpinnerKeyReleased

    private void inHourSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_inHourSpinnerStateChanged
        CalculationMaker.limitSpinnerValue(inHourSpinner, 1, 12);

    }//GEN-LAST:event_inHourSpinnerStateChanged

    private void inMinuteSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_inMinuteSpinnerStateChanged
        CalculationMaker.limitSpinnerValue(inMinuteSpinner, 0, 59);
    }//GEN-LAST:event_inMinuteSpinnerStateChanged

    private void outHourSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_outHourSpinnerStateChanged
        CalculationMaker.limitSpinnerValue(outHourSpinner, 1, 12);
    }//GEN-LAST:event_outHourSpinnerStateChanged

    private void outMinuteSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_outMinuteSpinnerStateChanged
        CalculationMaker.limitSpinnerValue(outMinuteSpinner, 0, 59);
    }//GEN-LAST:event_outMinuteSpinnerStateChanged

    private void inMinuteSpinnerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inMinuteSpinnerKeyReleased
        CalculationMaker.limitSpinnerValue(inMinuteSpinner, 0, 59);
    }//GEN-LAST:event_inMinuteSpinnerKeyReleased

    private void outHourSpinnerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_outHourSpinnerKeyReleased
        CalculationMaker.limitSpinnerValue(outHourSpinner, 1, 12);
    }//GEN-LAST:event_outHourSpinnerKeyReleased

    private void outMinuteSpinnerKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_outMinuteSpinnerKeyReleased
        CalculationMaker.limitSpinnerValue(outMinuteSpinner, 0, 59);
    }//GEN-LAST:event_outMinuteSpinnerKeyReleased

    private void outAmPmStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_outAmPmStateChanged
    }//GEN-LAST:event_outAmPmStateChanged

    private void outAmPmKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_outAmPmKeyReleased
    }//GEN-LAST:event_outAmPmKeyReleased

    private void instructorComboBoxAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorComboBoxAActionPerformed
       
            if (instructorComboBoxA.getSelectedItem().toString() != null) {
                 String  instructorSel = instructorComboBoxA.getSelectedItem().toString();
           StringTokenizer st=new StringTokenizer(instructorSel, "_");          
          String name=st.nextToken();
          instructorId=st.nextToken();
                
               
                insNameText.setText(name);
            } else {
                insNameText.setText(null);
            }
        
    }//GEN-LAST:event_instructorComboBoxAActionPerformed

    private void exitAButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitAButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitAButtonActionPerformed

    private void driLicNoTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_driLicNoTextKeyPressed
    }//GEN-LAST:event_driLicNoTextKeyPressed

    private void teachDriLicNoTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teachDriLicNoTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER | evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tdlExpireDateChooser.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            dlExpireDateChooser.requestFocus();
        }
    }//GEN-LAST:event_teachDriLicNoTextKeyPressed

    private void dlExpireDateTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dlExpireDateTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER | evt.getKeyCode() == KeyEvent.VK_DOWN) {
            teachDriLicNoTextR.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            driLicNoTextR.requestFocus();
        }
    }//GEN-LAST:event_dlExpireDateTextKeyPressed

    private void tdlExpireDateTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tdlExpireDateTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER | evt.getKeyCode() == KeyEvent.VK_DOWN) {
            tdlExpireDateChooser.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            dlExpireDateChooser.requestFocus();
        }
    }//GEN-LAST:event_tdlExpireDateTextKeyPressed

    private void driLicNoTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_driLicNoTextKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER | evt.getKeyCode() == KeyEvent.VK_DOWN) {
            dlExpireDateChooser.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
            nicTextR.requestFocus();
        }
    }//GEN-LAST:event_driLicNoTextKeyReleased

    private void tableAttendanceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tableAttendanceKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_DELETE) {
            int selectedRow = tableAttendance.getSelectedRow();
            if (selectedRow != -1) {
                dtm.removeRow(selectedRow);
            } else {
                JOptionPane.showMessageDialog(InstructorDetailManager.this, "Please select a row to delete");
            }
        }

    }//GEN-LAST:event_tableAttendanceKeyReleased
    private void addRowToTable() {

        timeIn = inHourSpinner.getValue().toString() + ":" + inMinuteSpinner.getValue().toString() + " " + inAmPm.getValue().toString();
        timeOut = outHourSpinner.getValue().toString() + ":" + outMinuteSpinner.getValue().toString() + " " + outAmPm.getValue().toString();
        dtm = (DefaultTableModel) tableAttendance.getModel();
        dtm.addRow(new Object[]{instructorId, instructorName, timeIn, timeOut});
        
        instructorComboBoxA.removeItemAt(instructorComboBoxA.getSelectedIndex());
    }

    private void addInstructorData() {
        try {
            if (instructorComboBox.getSelectedItem() != null) {
                String  instructorSel = instructorComboBox.getSelectedItem().toString();
           StringTokenizer st=new StringTokenizer(instructorSel, "_");          
          String name=st.nextToken();
          instructorId=st.nextToken();
          Instructor instructor=InstructorController.searchInstructor(instructorId);
                if (instructor != null) {
                    addressText.setText(instructor.getAddress());
                    nameEditText.setText(instructor.getName());
                    telephoneText.setText(instructor.getInstructorTel());
                    nicText.setText(instructor.getNic());
                    dateText.setText(instructor.getDateOfRegistration());
                    driLicNoText.setText(instructor.getDriverLicenceNo());
                    dlExpireDateText.setText(instructor.getDriverLicenceExpireDate());
                    teachDriLicNoText.setText(instructor.getTeachingLicenceNo());
                    tdlExpireDateText.setText(instructor.getTeachingLicenceExpireDate());
                    VehicleClassSet vehicleClassSet = VehicleClassController.searchVehicleClassSet(instructor.getClassId());
                    classText.setText(vehicleClassSet.getClassType());
                } else {
                    System.out.println("a");
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(InstructorDetailManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private Instructor getDataFromForm(String iid) throws ClassNotFoundException, SQLException {
        Instructor instructor = new Instructor();
        instructor.setInstructorId(iid);
        instructor.setName(nameWithInitialsTextR.getText());
        instructor.setAddress(addressTextR.getText());
        instructor.setInstructorTel(telephoneTextR.getText());
        instructor.setNic(nicTextR.getText());
        Date date = dateChooser.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        instructor.setDateOfRegistration(sdf.format(date));
        instructor.setDriverLicenceNo(driLicNoTextR.getText());
        if (dlExpireDateChooser.getDate() != null) {
            Date dateExp = dlExpireDateChooser.getDate();
            instructor.setDriverLicenceExpireDate(sdf.format(dateExp));
        }
        instructor.setTeachingLicenceNo(teachDriLicNoTextR.getText());
        if (tdlExpireDateChooser.getDate() != null) {
            Date dateTDl = tdlExpireDateChooser.getDate();
            instructor.setTeachingLicenceExpireDate(sdf.format(dateTDl));
        }
        VehicleClassSet vehicleClassSet = VehicleClassController.searchVehicleClassSetByName(classComboBox1.getSelectedItem().toString());
        instructor.setClassId(vehicleClassSet.getClassId());
        return instructor;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabel1;
    private javax.swing.JTextField addressText;
    private javax.swing.JTextField addressTextR;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox classComboBox1;
    private javax.swing.JLabel classLabel;
    private javax.swing.JLabel classLabel2;
    private javax.swing.JTextField classText;
    private com.toedter.calendar.JDateChooser dateChooser;
    private com.toedter.calendar.JDateChooser dateChooserM;
    private javax.swing.JTextField dateText;
    private javax.swing.JToggleButton deleteButton;
    private com.toedter.calendar.JDateChooser dlExpireDateChooser;
    private javax.swing.JLabel dlExpireDateLabel;
    private javax.swing.JTextField dlExpireDateText;
    private javax.swing.JTextField driLicNoText;
    private javax.swing.JTextField driLicNoTextR;
    private javax.swing.JButton exitAButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitButtonR;
    private javax.swing.JTextField iidTextR;
    private javax.swing.JSpinner inAmPm;
    private javax.swing.JSpinner inHourSpinner;
    private javax.swing.JSpinner inMinuteSpinner;
    private javax.swing.JTextField insNameText;
    private javax.swing.JComboBox instructorComboBox;
    private javax.swing.JComboBox instructorComboBoxA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel nameEditLabel;
    private javax.swing.JTextField nameEditText;
    private javax.swing.JLabel nameText;
    private javax.swing.JLabel nameWithInitialsLabel1;
    private javax.swing.JTextField nameWithInitialsTextR;
    private javax.swing.JLabel nicLabel;
    private javax.swing.JLabel nicLabel1;
    private javax.swing.JTextField nicText;
    private javax.swing.JTextField nicTextR;
    private javax.swing.JSpinner outAmPm;
    private javax.swing.JSpinner outHourSpinner;
    private javax.swing.JSpinner outMinuteSpinner;
    private javax.swing.JPanel registerNewInstructor;
    private javax.swing.JButton saveAButton;
    private javax.swing.JToggleButton saveButton;
    private javax.swing.JTable tableAttendance;
    private com.toedter.calendar.JDateChooser tdlExpireDateChooser;
    private javax.swing.JLabel tdlExpireDateLabel;
    private javax.swing.JTextField tdlExpireDateText;
    private javax.swing.JTextField teachDriLicNoText;
    private javax.swing.JTextField teachDriLicNoTextR;
    private javax.swing.JLabel teachLicNoLabel;
    private javax.swing.JLabel telLabel;
    private javax.swing.JLabel telLabel1;
    private javax.swing.JTextField telephoneText;
    private javax.swing.JTextField telephoneTextR;
    private javax.swing.JToggleButton updateButton;
    private javax.swing.JPanel updateInstructorPanel;
    // End of variables declaration//GEN-END:variables
}
