/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dsms.views;

import com.jpackages.jflashplayer.FlashPanel;
import com.jpackages.jflashplayer.JFlashInvalidFlashException;
import com.jpackages.jflashplayer.JFlashLibraryLoadFailedException;
import dsms.common_classes.CalculationMaker;
import dsms.common_classes.ComboItemsAdder;
import dsms.common_classes.ComboSearch;
import dsms.controllers.*;
import dsms.models.*;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/**
 *
 * @author User
 */
public class StartAdmin extends javax.swing.JFrame {

    String user;

    /**
     * Creates new form StartAdmin
     */
    public StartAdmin(String user) {
        this.user = user;
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/dsms/images/logo30.jpg"));
        setIconImage(icon1.getImage());
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        try {
            ComboItemsAdder.addAllStudentID(studentIDCombo);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StartAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        ComboSearch.setSearchableCombo(studentIDCombo, true, "no result!");
        
//            FlashPanel fp = null;
//        try {
//            fp = new FlashPanel(new File("src/dsms/images/clock102.swf"));
//        } catch (JFlashLibraryLoadFailedException | JFlashInvalidFlashException | FileNotFoundException ex) {
//            Logger.getLogger(StartAdmin.class.getName()).log(Level.SEVERE, null, ex);
//        }
//            fp.setBackground(clockpanel.getBackground());
//            clockpanel.add(fp);
//            fp.play();

    }

    public StartAdmin() {
         this.user = user;
        ImageIcon icon1 = new ImageIcon(getClass().getResource("/dsms/images/logo30.jpg"));
        setIconImage(icon1.getImage());
        initComponents();
        setSize(Toolkit.getDefaultToolkit().getScreenSize());
        try {
            ComboItemsAdder.addAllStudentID(studentIDCombo);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StartAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
        ComboSearch.setSearchableCombo(studentIDCombo, true, "no result!");
        
//            FlashPanel fp = null;
//        try {
//            fp = new FlashPanel(new File("src/dsms/images/clock102.swf"));
//        } catch (JFlashLibraryLoadFailedException | JFlashInvalidFlashException | FileNotFoundException ex) {
//            Logger.getLogger(StartAdmin.class.getName()).log(Level.SEVERE, null, ex);
//        }
//            fp.setBackground(clockpanel.getBackground());
//            clockpanel.add(fp);
//            fp.play();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        desktopPane = new javax.swing.JDesktopPane();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        trialResultText = new javax.swing.JTextField();
        examDateText = new javax.swing.JTextField();
        statusText = new javax.swing.JTextField();
        examResultText = new javax.swing.JTextField();
        trialDateText = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        vehicleClassText = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        instructorText = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        noOfDaysText = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        totalFeeText = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        balanceText = new javax.swing.JTextField();
        studentIDCombo = new javax.swing.JComboBox();
        courseDetailButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        clockPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        registerNewStudentButton = new javax.swing.JButton();
        paymentButton = new javax.swing.JButton();
        attendanceButton = new javax.swing.JButton();
        studentButton = new javax.swing.JButton();
        resultButton1 = new javax.swing.JButton();
        resultButton = new javax.swing.JButton();
        clockpanel = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        studentMenu = new javax.swing.JMenu();
        registerNewStudentMenu = new javax.swing.JMenuItem();
        detailManageMenu = new javax.swing.JMenuItem();
        studentAttendanceMenu = new javax.swing.JMenu();
        markAttendMenu = new javax.swing.JMenuItem();
        viewAttendMenu = new javax.swing.JMenuItem();
        instructorMenu = new javax.swing.JMenu();
        registerNewInstructorButton = new javax.swing.JMenuItem();
        insDetailManager = new javax.swing.JMenu();
        searchInsMenu = new javax.swing.JMenuItem();
        updateInsMenu = new javax.swing.JMenuItem();
        deleteInsMenu = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        paymentMenu = new javax.swing.JMenu();
        newPaymentMenu = new javax.swing.JMenuItem();
        searchPaymentMenu = new javax.swing.JMenuItem();
        changePaymentMenu = new javax.swing.JMenuItem();
        pendingMenu = new javax.swing.JMenuItem();
        viewAllPaymentMenu = new javax.swing.JMenuItem();
        vehicleClassInfoMenu = new javax.swing.JMenu();
        viewClassInfoMenu = new javax.swing.JMenuItem();
        updateClassInfoMenu = new javax.swing.JMenuItem();
        resultMenu = new javax.swing.JMenu();
        examMenu = new javax.swing.JMenu();
        enterExamResultMenu = new javax.swing.JMenuItem();
        viewExamResultMenu = new javax.swing.JMenuItem();
        trialMenu = new javax.swing.JMenu();
        enterTrialResultMenu = new javax.swing.JMenuItem();
        viewTrialResultMenu = new javax.swing.JMenuItem();
        progressMenu = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setOpaque(false);

        jXPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jXPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setBackground(new java.awt.Color(102, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Enter Id:");

        jLabel2.setText("Name:");

        jLabel5.setText("Trial Results:");

        jLabel6.setText("Status:");

        jLabel7.setText("Trial date:");

        jLabel8.setText("Exam Results:");

        jLabel9.setText("Exam date:");

        jLabel10.setText("Vehicle Class:");

        jLabel11.setText("Instructor:");

        jLabel12.setText("No. of days came:");

        jLabel13.setText("out of 15");

        jLabel14.setText("Total fee:");

        jLabel15.setText("Balance to pay:");

        studentIDCombo.setEditable(true);
        studentIDCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(studentIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(trialDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(trialResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(examResultText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(examDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(vehicleClassText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(18, 18, 18)
                                .addComponent(instructorText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(noOfDaysText, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(totalFeeText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(balanceText, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(studentIDCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(39, 39, 39)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(examDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(examResultText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(trialDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(trialResultText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(vehicleClassText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(instructorText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noOfDaysText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(totalFeeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(balanceText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        courseDetailButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        courseDetailButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/images/info.jpg"))); // NOI18N
        courseDetailButton.setText("Classes & fees details");
        courseDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseDetailButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(jXPanel1Layout.createSequentialGroup()
                        .addComponent(courseDetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(courseDetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/images/Driving.jpg"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Stamp", 1, 36)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/images/editted.jpg"))); // NOI18N
        jLabel4.setText("Wiraja Driving School");

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Goverment Approval Grade 'A'| No.49,New Tangalle rd,Kotuwegoda,Matara|0413414808");
        jLabel16.setOpaque(true);

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new java.awt.GridLayout(6, 1, 10, 10));

        registerNewStudentButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        registerNewStudentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/images/STUDENT (2).jpg"))); // NOI18N
        registerNewStudentButton.setText("Register new student");
        registerNewStudentButton.setBorderPainted(false);
        registerNewStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerNewStudentButtonActionPerformed(evt);
            }
        });
        jPanel2.add(registerNewStudentButton);

        paymentButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        paymentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/images/payment-icon.gif"))); // NOI18N
        paymentButton.setText("New Payment           ");
        paymentButton.setBorderPainted(false);
        paymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentButtonActionPerformed(evt);
            }
        });
        jPanel2.add(paymentButton);

        attendanceButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        attendanceButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/images/attendance.png"))); // NOI18N
        attendanceButton.setText("Attendance            ");
        attendanceButton.setBorderPainted(false);
        attendanceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendanceButtonActionPerformed(evt);
            }
        });
        jPanel2.add(attendanceButton);

        studentButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        studentButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/images/student.jpg"))); // NOI18N
        studentButton.setText("Student Details       ");
        studentButton.setBorderPainted(false);
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButtonActionPerformed(evt);
            }
        });
        jPanel2.add(studentButton);

        resultButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resultButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/images/teacher_icon.jpg"))); // NOI18N
        resultButton1.setText("Instructors Details   ");
        resultButton1.setBorderPainted(false);
        resultButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(resultButton1);

        resultButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        resultButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/images/results_icon.jpg"))); // NOI18N
        resultButton.setText("Exam & Trial Details  ");
        resultButton.setBorderPainted(false);
        resultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultButtonActionPerformed(evt);
            }
        });
        jPanel2.add(resultButton);

        javax.swing.GroupLayout clockPanelLayout = new javax.swing.GroupLayout(clockPanel);
        clockPanel.setLayout(clockPanelLayout);
        clockPanelLayout.setHorizontalGroup(
            clockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clockPanelLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        clockPanelLayout.setVerticalGroup(
            clockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clockPanelLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton1.setText("Trial List");

        jButton2.setText("jButton1");

        javax.swing.GroupLayout clockpanelLayout = new javax.swing.GroupLayout(clockpanel);
        clockpanel.setLayout(clockpanelLayout);
        clockpanelLayout.setHorizontalGroup(
            clockpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clockpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        clockpanelLayout.setVerticalGroup(
            clockpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clockpanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(clockpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        studentMenu.setText("Student");

        registerNewStudentMenu.setText("Register new");
        registerNewStudentMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerNewStudentMenuActionPerformed(evt);
            }
        });
        studentMenu.add(registerNewStudentMenu);

        detailManageMenu.setText("Detail Manager");
        detailManageMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailManageMenuActionPerformed(evt);
            }
        });
        studentMenu.add(detailManageMenu);

        studentAttendanceMenu.setText("Attendance");

        markAttendMenu.setText("Mark Atten:");
        markAttendMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                markAttendMenuActionPerformed(evt);
            }
        });
        studentAttendanceMenu.add(markAttendMenu);

        viewAttendMenu.setText("View Atten:");
        viewAttendMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAttendMenuActionPerformed(evt);
            }
        });
        studentAttendanceMenu.add(viewAttendMenu);

        studentMenu.add(studentAttendanceMenu);

        jMenuBar1.add(studentMenu);

        instructorMenu.setText("Instructor");

        registerNewInstructorButton.setText("Register new");
        registerNewInstructorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerNewInstructorButtonActionPerformed(evt);
            }
        });
        instructorMenu.add(registerNewInstructorButton);

        insDetailManager.setText("Detail Manager");

        searchInsMenu.setText("Search");
        searchInsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchInsMenuActionPerformed(evt);
            }
        });
        insDetailManager.add(searchInsMenu);

        updateInsMenu.setText("Update");
        updateInsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInsMenuActionPerformed(evt);
            }
        });
        insDetailManager.add(updateInsMenu);

        deleteInsMenu.setText("Delete");
        deleteInsMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteInsMenuActionPerformed(evt);
            }
        });
        insDetailManager.add(deleteInsMenu);

        instructorMenu.add(insDetailManager);

        jMenu8.setText("Attendance");

        jMenuItem9.setText("Mark Atten:");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem9);

        jMenuItem10.setText("View Atten:");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem10);

        instructorMenu.add(jMenu8);

        jMenuBar1.add(instructorMenu);

        paymentMenu.setText("Payments");

        newPaymentMenu.setText("New Payment");
        newPaymentMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPaymentMenuActionPerformed(evt);
            }
        });
        paymentMenu.add(newPaymentMenu);

        searchPaymentMenu.setText("Search payments");
        searchPaymentMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchPaymentMenuActionPerformed(evt);
            }
        });
        paymentMenu.add(searchPaymentMenu);

        changePaymentMenu.setText("Change payment");
        changePaymentMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePaymentMenuActionPerformed(evt);
            }
        });
        paymentMenu.add(changePaymentMenu);

        pendingMenu.setText("Pendings");
        pendingMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pendingMenuActionPerformed(evt);
            }
        });
        paymentMenu.add(pendingMenu);

        viewAllPaymentMenu.setText("View all payments");
        paymentMenu.add(viewAllPaymentMenu);

        jMenuBar1.add(paymentMenu);

        vehicleClassInfoMenu.setText("Vehicle Class Info:");

        viewClassInfoMenu.setText("View Info:");
        viewClassInfoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewClassInfoMenuActionPerformed(evt);
            }
        });
        vehicleClassInfoMenu.add(viewClassInfoMenu);

        updateClassInfoMenu.setText("Update info:");
        updateClassInfoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateClassInfoMenuActionPerformed(evt);
            }
        });
        vehicleClassInfoMenu.add(updateClassInfoMenu);

        jMenuBar1.add(vehicleClassInfoMenu);

        resultMenu.setText("Results");

        examMenu.setText("Exam");

        enterExamResultMenu.setText("Enter results");
        enterExamResultMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterExamResultMenuActionPerformed(evt);
            }
        });
        examMenu.add(enterExamResultMenu);

        viewExamResultMenu.setText("View results");
        viewExamResultMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewExamResultMenuActionPerformed(evt);
            }
        });
        examMenu.add(viewExamResultMenu);

        resultMenu.add(examMenu);

        trialMenu.setText("Trial");

        enterTrialResultMenu.setText("Enter results");
        enterTrialResultMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterTrialResultMenuActionPerformed(evt);
            }
        });
        trialMenu.add(enterTrialResultMenu);

        viewTrialResultMenu.setText("View results");
        viewTrialResultMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTrialResultMenuActionPerformed(evt);
            }
        });
        trialMenu.add(viewTrialResultMenu);

        resultMenu.add(trialMenu);

        progressMenu.setText("Progress");
        progressMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressMenuActionPerformed(evt);
            }
        });

        jMenuItem26.setText("jMenuItem26");
        progressMenu.add(jMenuItem26);

        resultMenu.add(progressMenu);

        jMenuBar1.add(resultMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(clockpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desktopPane)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)))
                .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 350, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 351, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(69, 69, 69))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(desktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(clockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clockpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 82, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 82, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerNewStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerNewStudentButtonActionPerformed
        desktopPane.removeAll();
        StudentRegistration sg = new StudentRegistration();
        sg.setSize(desktopPane.getSize());
        desktopPane.add(sg);
        sg.setVisible(true);
        // new StudentRegistration(StartAdmin.this, true).setVisible(true);
    }//GEN-LAST:event_registerNewStudentButtonActionPerformed

    private void paymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentButtonActionPerformed
        desktopPane.removeAll();
        PaymentOfStudent paymentOfStudent = new PaymentOfStudent(StartAdmin.this);
        paymentOfStudent.setSize(desktopPane.getSize());

        desktopPane.add(paymentOfStudent);
        paymentOfStudent.setVisible(true);
    }//GEN-LAST:event_paymentButtonActionPerformed

    private void attendanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendanceButtonActionPerformed
        desktopPane.removeAll();
        StudentAttendanceI studentAttendanceI = new StudentAttendanceI();
        studentAttendanceI.setSize(desktopPane.getSize());

        desktopPane.add(studentAttendanceI);
        studentAttendanceI.setVisible(true);
    }//GEN-LAST:event_attendanceButtonActionPerformed

    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
        desktopPane.removeAll();
        StudentDetailManager studentDetailManager = new StudentDetailManager();
        studentDetailManager.setSize(desktopPane.getSize());

        desktopPane.add(studentDetailManager);
        studentDetailManager.setVisible(true);
        // new PendingPayment(StartAdmin.this, true).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_studentButtonActionPerformed

    private void courseDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseDetailButtonActionPerformed
      //  new VehicleClassInformation(StartAdmin.this, true).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_courseDetailButtonActionPerformed

    private void resultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultButtonActionPerformed
        desktopPane.removeAll();
        ExamTrialDetail examTrialDetail = new ExamTrialDetail();
        examTrialDetail.setSize(desktopPane.getSize());

        desktopPane.add(examTrialDetail);
        examTrialDetail.setVisible(true);
    }//GEN-LAST:event_resultButtonActionPerformed

    private void registerNewStudentMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerNewStudentMenuActionPerformed
        //
    }//GEN-LAST:event_registerNewStudentMenuActionPerformed

    private void markAttendMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_markAttendMenuActionPerformed
        //   new StudentAttendance(StartAdmin.this, true).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_markAttendMenuActionPerformed

    private void viewAttendMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAttendMenuActionPerformed
        // new StudentAttendance(StartAdmin.this, true).setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_viewAttendMenuActionPerformed

    private void registerNewInstructorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerNewInstructorButtonActionPerformed
        //new AddNewInstructor(StartAdmin.this, true).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_registerNewInstructorButtonActionPerformed

    private void searchInsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchInsMenuActionPerformed
//        InstructorDetails iu = new InstructorDetails(StartAdmin.this, true);
//        iu.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_searchInsMenuActionPerformed

    private void updateInsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInsMenuActionPerformed
//        InstructorDetails iu = new InstructorDetails(StartAdmin.this, true);
//        iu.setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_updateInsMenuActionPerformed

    private void deleteInsMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteInsMenuActionPerformed
//        InstructorDetails iu = new InstructorDetails(StartAdmin.this, true);
//        iu.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_deleteInsMenuActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        //  new InstructorAttendanceV(StartAdmin.this, true).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        //   new InstructorAttendanceV(StartAdmin.this, true).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void newPaymentMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPaymentMenuActionPerformed
//        new PaymentOfStudent(StartAdmin.this, true).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_newPaymentMenuActionPerformed

    private void searchPaymentMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchPaymentMenuActionPerformed
        //       new PaymentOfStudent(StartAdmin.this, true).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_searchPaymentMenuActionPerformed

    private void changePaymentMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePaymentMenuActionPerformed
        //       new PaymentOfStudent(StartAdmin.this, true).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_changePaymentMenuActionPerformed

    private void pendingMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pendingMenuActionPerformed
     //   new PendingPayment(StartAdmin.this, true).setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_pendingMenuActionPerformed

    private void viewClassInfoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewClassInfoMenuActionPerformed
    //    new VehicleClassInformation(StartAdmin.this, true).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_viewClassInfoMenuActionPerformed

    private void updateClassInfoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateClassInfoMenuActionPerformed
   //     new VehicleClassInformation(StartAdmin.this, true).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_updateClassInfoMenuActionPerformed

    private void enterExamResultMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterExamResultMenuActionPerformed
        //   new EnterResults(StartAdmin.this, true).setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_enterExamResultMenuActionPerformed

    private void viewExamResultMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewExamResultMenuActionPerformed
        //   new ViewResults(StartAdmin.this, true).setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_viewExamResultMenuActionPerformed

    private void enterTrialResultMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterTrialResultMenuActionPerformed
        //  new EnterResults(StartAdmin.this, true).setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_enterTrialResultMenuActionPerformed

    private void viewTrialResultMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTrialResultMenuActionPerformed
        // new EnterResults(StartAdmin.this, true).setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_viewTrialResultMenuActionPerformed

    private void progressMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressMenuActionPerformed
//        new ViewProgress(StartAdmin.this, true).setVisible(true); // TODO add your handling code here:
    }//GEN-LAST:event_progressMenuActionPerformed

    private void resultButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultButton1ActionPerformed
        desktopPane.removeAll();
        InstructorDetailManager instructorDetailManager = new InstructorDetailManager();
        instructorDetailManager.setSize(desktopPane.getSize());
        instructorDetailManager.setVisible(true);
        desktopPane.add(instructorDetailManager);
    }//GEN-LAST:event_resultButton1ActionPerformed

    private void detailManageMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailManageMenuActionPerformed
        StudentDetailManager studentDetailManager = new StudentDetailManager();
        studentDetailManager.setVisible(true);
    }//GEN-LAST:event_detailManageMenuActionPerformed

    private void studentIDComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDComboActionPerformed
        try {

            String sid = studentIDCombo.getSelectedItem().toString();
            Student student = StudentController.searchStudent(sid);
            nameText.setText(student.getNameWithInitials());

            Registration registration = RegistrationController.searchLastRegistration(sid);
            int status = registration.getStatus();
            if (status == 1) {
                statusText.setText("Training");
            } else if (status == 0) {
                statusText.setText("Finished");
            }
            VehicleClassSet classSet = VehicleClassController.searchVehicleClassSet(registration.getClassId());
            vehicleClassText.setText(classSet.getClassType());
            Instructor instructor = InstructorController.searchInstructor(registration.getInstructorId());
            instructorText.setText(instructor.getName());
            int noOfDays = 0;
            noOfDays = StudentAttendanceController.getAttendanceCount(registration);
            noOfDaysText.setText(Integer.toString(noOfDays));
            totalFeeText.setText(Double.toString(registration.getTotalFee()));
            double paidTotal = CalculationMaker.paymentsAdder(registration.getRegistrationId());
            balanceText.setText(Double.toString(registration.getTotalFee() - paidTotal));
            ExamDetail examDetail = ExamDetailController.searchLastExamResult(registration.getRegistrationId());
            if (examDetail != null) {
                examDateText.setText(examDetail.getDate());
                if (examDetail.getResult() == 0) {
                    examResultText.setText("Not paiticipated");
                } else if (examDetail.getResult() == 1) {
                    examResultText.setText("Passed");
                } else if (examDetail.getResult() == -1) {
                    examResultText.setText("Failed");
                }

            } else {
                examDateText.setText("Not yet");
                examResultText.setText("Not yet");
            }
            TrialDetail trialDetail = TrialDetailController.searchLastTrialResult(registration.getRegistrationId());
            if (trialDetail != null) {
                trialDateText.setText(trialDetail.getDate());
                if (trialDetail.getResult() == 0) {
                    trialResultText.setText("Not paiticipated");
                } else if (trialDetail.getResult() == 1) {
                    trialResultText.setText("Passed");
                } else if (trialDetail.getResult() == -1) {
                    trialResultText.setText("Failed");
                }

            } else {
                trialDateText.setText("Not yet");
                trialResultText.setText("Not yet");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StartAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_studentIDComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new StartAdmin().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attendanceButton;
    private javax.swing.JTextField balanceText;
    private javax.swing.JMenuItem changePaymentMenu;
    private javax.swing.JPanel clockPanel;
    private javax.swing.JPanel clockpanel;
    private javax.swing.JButton courseDetailButton;
    private javax.swing.JMenuItem deleteInsMenu;
    public javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem detailManageMenu;
    private javax.swing.JMenuItem enterExamResultMenu;
    private javax.swing.JMenuItem enterTrialResultMenu;
    private javax.swing.JTextField examDateText;
    private javax.swing.JMenu examMenu;
    private javax.swing.JTextField examResultText;
    private javax.swing.JMenu insDetailManager;
    private javax.swing.JMenu instructorMenu;
    private javax.swing.JTextField instructorText;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    private javax.swing.JMenuItem markAttendMenu;
    private javax.swing.JTextField nameText;
    private javax.swing.JMenuItem newPaymentMenu;
    private javax.swing.JTextField noOfDaysText;
    private javax.swing.JButton paymentButton;
    private javax.swing.JMenu paymentMenu;
    private javax.swing.JMenuItem pendingMenu;
    private javax.swing.JMenu progressMenu;
    private javax.swing.JMenuItem registerNewInstructorButton;
    public javax.swing.JButton registerNewStudentButton;
    private javax.swing.JMenuItem registerNewStudentMenu;
    private javax.swing.JButton resultButton;
    private javax.swing.JButton resultButton1;
    private javax.swing.JMenu resultMenu;
    private javax.swing.JMenuItem searchInsMenu;
    private javax.swing.JMenuItem searchPaymentMenu;
    private javax.swing.JTextField statusText;
    private javax.swing.JMenu studentAttendanceMenu;
    private javax.swing.JButton studentButton;
    private javax.swing.JComboBox studentIDCombo;
    private javax.swing.JMenu studentMenu;
    private javax.swing.JTextField totalFeeText;
    private javax.swing.JTextField trialDateText;
    private javax.swing.JMenu trialMenu;
    private javax.swing.JTextField trialResultText;
    private javax.swing.JMenuItem updateClassInfoMenu;
    private javax.swing.JMenuItem updateInsMenu;
    private javax.swing.JMenu vehicleClassInfoMenu;
    private javax.swing.JTextField vehicleClassText;
    private javax.swing.JMenuItem viewAllPaymentMenu;
    private javax.swing.JMenuItem viewAttendMenu;
    private javax.swing.JMenuItem viewClassInfoMenu;
    private javax.swing.JMenuItem viewExamResultMenu;
    private javax.swing.JMenuItem viewTrialResultMenu;
    // End of variables declaration//GEN-END:variables
}
