/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dsms.views;

import dsms.common_classes.ComboItemsAdder;
import dsms.controllers.InstructorController;
import dsms.controllers.RegistrationController;
import dsms.controllers.StudentAttendanceController;
import dsms.controllers.StudentController;
import dsms.models.Instructor;
import dsms.models.Registration;
import dsms.models.Student;
import dsms.models.StudentAttendance;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class StudentAttendanceI extends javax.swing.JInternalFrame {

    DefaultTableModel dtm, dtmV;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form StudentAttendanceI
     */
    public StudentAttendanceI() {
        try {
            initComponents();
            ////////////////////////////////
            ComboItemsAdder.addAllInstructorsId(instructorCombo);
            dateChooserM.setDate(new Date());
            alreadyLabel.setVisible(false);
            studentOwn.setSelected(true);
            ///////////////////////////
            dateChooserV.setDate(new Date());
            addAttendanceToTable();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(StudentAttendanceI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void requestFocusForm() {
        dateChooserM.requestFocus();
    }

    private void addAttendanceToTable() {
        String date = sdf.format(dateChooserV.getDate());
        try {
            dtmV = (DefaultTableModel) attendanceEditTable.getModel();
            ArrayList<StudentAttendance> attendances = StudentAttendanceController.searchAttendanceOfDate(date);
            for (StudentAttendance attendance : attendances) {
                Instructor instructor = InstructorController.searchInstructor(attendance.getInstructorId());
                Registration registration = RegistrationController.searchRegistration(attendance.getRegistrationId());
                Student student = StudentController.searchStudent(registration.getStudentId());
                dtm = (DefaultTableModel) attendanceTable.getModel();
                dtmV.addRow(new Object[]{attendance.getTurn(), student.getStudentId(), student.getNameWithInitials(), attendance.getInstructorId(), instructor.getName()});
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StudentAttendanceI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        dateChooserM = new com.toedter.calendar.JDateChooser();
        turnLabel = new javax.swing.JLabel();
        turnCombo = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        instructorCombo = new javax.swing.JComboBox();
        studentLabel = new javax.swing.JLabel();
        ownStudentCombo = new javax.swing.JComboBox();
        addButton = new javax.swing.JButton();
        instructorNameText = new javax.swing.JTextField();
        ownStudentNameText = new javax.swing.JTextField();
        alreadyLabel = new javax.swing.JLabel();
        studentOwn = new javax.swing.JRadioButton();
        studentOther = new javax.swing.JRadioButton();
        otherStudentCombo = new javax.swing.JComboBox();
        otherStudentNameText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        attendanceTable = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        saveButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        dateChooserV = new com.toedter.calendar.JDateChooser();
        dateVLabel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        attendanceEditTable = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        exitButton1 = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        dateLabel.setText("Date:");

        dateChooserM.setDateFormatString("yyyy-MM-dd");

        turnLabel.setText("Turn:");

        turnCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "6.00am", "7.00am", "10.00am", "2.10pm", "4.00pm" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(dateChooserM, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(turnLabel)
                .addGap(18, 18, 18)
                .addComponent(turnCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(turnLabel)
                        .addComponent(turnCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(dateChooserM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dateLabel)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel1.setText("Instructor:");

        instructorCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                instructorComboItemStateChanged(evt);
            }
        });
        instructorCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorComboActionPerformed(evt);
            }
        });

        studentLabel.setText("Student:");

        ownStudentCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ownStudentComboItemStateChanged(evt);
            }
        });
        ownStudentCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ownStudentComboKeyPressed(evt);
            }
        });

        addButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Plus.png"))); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        instructorNameText.setEditable(false);
        instructorNameText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                instructorNameTextKeyReleased(evt);
            }
        });

        ownStudentNameText.setEditable(false);

        alreadyLabel.setBackground(new java.awt.Color(255, 255, 255));
        alreadyLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        alreadyLabel.setForeground(new java.awt.Color(255, 0, 0));
        alreadyLabel.setText("Already Added!");

        buttonGroup1.add(studentOwn);
        studentOwn.setText("Own Students");
        studentOwn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentOwnActionPerformed(evt);
            }
        });

        buttonGroup1.add(studentOther);
        studentOther.setText("Other Students");
        studentOther.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentOtherActionPerformed(evt);
            }
        });

        otherStudentCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                otherStudentComboItemStateChanged(evt);
            }
        });
        otherStudentCombo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                otherStudentComboKeyPressed(evt);
            }
        });

        otherStudentNameText.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(studentLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(instructorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(instructorNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(studentOwn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ownStudentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ownStudentNameText)
                                .addGap(115, 115, 115))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(studentOther)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(otherStudentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(otherStudentNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                .addGap(15, 15, 15)
                                .addComponent(addButton)
                                .addGap(29, 29, 29)))
                        .addComponent(alreadyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(instructorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(instructorNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(studentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentOwn)
                            .addComponent(ownStudentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ownStudentNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentOther)
                            .addComponent(otherStudentCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(otherStudentNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(alreadyLabel)
                            .addComponent(addButton))))
                .addContainerGap())
        );

        attendanceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Turn", "Student ID", "InstructorID"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        attendanceTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(attendanceTable);
        attendanceTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        attendanceTable.getColumnModel().getColumn(1).setPreferredWidth(10);
        attendanceTable.getColumnModel().getColumn(2).setPreferredWidth(5);
        attendanceTable.getColumnModel().getColumn(3).setPreferredWidth(5);

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel7.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Save.png"))); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jPanel7.add(saveButton);

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Cancel.png"))); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel7.add(exitButton);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Mark Attendance", new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/to_do_list_cheked_all.png")), jPanel2); // NOI18N

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        dateChooserV.setDateFormatString("yyyy-MM-dd");
        dateChooserV.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateChooserVPropertyChange(evt);
            }
        });
        dateChooserV.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                dateChooserVKeyReleased(evt);
            }
        });

        dateVLabel.setText("Select Date:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(dateVLabel)
                .addGap(28, 28, 28)
                .addComponent(dateChooserV, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateChooserV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateVLabel))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        attendanceEditTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Turn", "Stu.Id", "Student", "Ins.Id", "Instructor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(attendanceEditTable);

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        exitButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exitButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/16x16/Cancel.png"))); // NOI18N
        exitButton1.setText("Exit");
        exitButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(exitButton1);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("View  Attendance", new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/View.png")), jPanel5); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        int j = 0, availableCount = 0;
        for (int i = 0; i < dtm.getRowCount(); i++) {
            try {
                Instructor instructor = InstructorController.searchInstructor(dtm.getValueAt(i, 3).toString());
                Registration registration = RegistrationController.searchRegistration(dtm.getValueAt(i, 2).toString(), instructor.getClassId());
                StudentAttendance studentAttendance = new StudentAttendance(registration.getRegistrationId(), dtm.getValueAt(i, 3).toString(), dtm.getValueAt(i, 0).toString(), dtm.getValueAt(i, 1).toString());
                boolean isPresent = StudentAttendanceController.searchAttendance(studentAttendance);
                if (isPresent == true) {
                    availableCount++;

                } else {
                    j += StudentAttendanceController.addStudentAttendance(studentAttendance);
                }
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(StudentAttendanceI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (j == (dtm.getRowCount() - availableCount)) {
            JOptionPane.showMessageDialog(StudentAttendanceI.this, "Attendance saved!");
        }
        dtm.setRowCount(0);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitButtonActionPerformed
    int sameRow = 0;
    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        Date date = dateChooserM.getDate();

        String dateS = sdf.format(date);
        dtm = (DefaultTableModel) attendanceTable.getModel();
        if (dtm.getRowCount() > 0) {
            for (int i = 0; i < dtm.getRowCount(); i++) {
                if (dateS.equals(dtm.getValueAt(i, 0).toString())
                        & turnCombo.getSelectedItem().toString().equals(dtm.getValueAt(i, 1).toString())
                        & getStudent().equals(dtm.getValueAt(i, 2).toString())
                        & instructorCombo.getSelectedItem().toString().equals(dtm.getValueAt(i, 3).toString())) {
                    sameRow++;
                }
            }
            if (sameRow == 0) {

                dtm.addRow(new Object[]{dateS, turnCombo.getSelectedItem().toString(), getStudent(), instructorCombo.getSelectedItem().toString()});
                alreadyLabel.setVisible(false);
            } else {
                alreadyLabel.setVisible(true);
            }
            sameRow = 0;
        } else if (dtm.getRowCount() == 0) {
            dtm.addRow(new Object[]{dateS, turnCombo.getSelectedItem().toString(), getStudent(), instructorCombo.getSelectedItem().toString()});

            alreadyLabel.setVisible(false);
        }
    }//GEN-LAST:event_addButtonActionPerformed
    private String getStudent() {
        String studentId = null;
        if (studentOwn.isSelected()) {
            studentId = ownStudentCombo.getSelectedItem().toString();
        } else if (studentOther.isSelected()) {
            studentId = otherStudentCombo.getSelectedItem().toString();
        }
        return studentId;
    }
    private void ownStudentComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ownStudentComboKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addButton.doClick();
        }
    }//GEN-LAST:event_ownStudentComboKeyPressed

    private void ownStudentComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ownStudentComboItemStateChanged
        try {
            if (ownStudentCombo.getSelectedItem() != null) {
                Student student = StudentController.searchStudent(ownStudentCombo.getSelectedItem().toString());
                ownStudentNameText.setText(student.getNameWithInitials());
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StudentAttendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ownStudentComboItemStateChanged

    private void instructorComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorComboActionPerformed
        try {
            ComboItemsAdder.getStudentsOfInstructors(ownStudentCombo, instructorCombo.getSelectedItem().toString());
            ComboItemsAdder.addAllStudentIDTraining(otherStudentCombo);
            Instructor instructor = InstructorController.searchInstructor(instructorCombo.getSelectedItem().toString());
            instructorNameText.setText(instructor.getName());
            if (ownStudentCombo.getSelectedItem() == null) {
                ownStudentNameText.setText(null);
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StudentAttendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_instructorComboActionPerformed

    private void instructorComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_instructorComboItemStateChanged
   }//GEN-LAST:event_instructorComboItemStateChanged

    private void instructorNameTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_instructorNameTextKeyReleased
    }//GEN-LAST:event_instructorNameTextKeyReleased

    private void dateChooserVKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dateChooserVKeyReleased
        Date date = dateChooserV.getDate();
        try {
            ArrayList<StudentAttendance> studentAttendSet = StudentAttendanceController.searchAttendanceOfDate(sdf.format(date));
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StudentAttendanceI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_dateChooserVKeyReleased

    private void otherStudentComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_otherStudentComboItemStateChanged
        try {
            if (otherStudentCombo.getSelectedItem() != null) {
                Student student = StudentController.searchStudent(otherStudentCombo.getSelectedItem().toString());
                otherStudentNameText.setText(student.getNameWithInitials());
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(StudentAttendance.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_otherStudentComboItemStateChanged

    private void otherStudentComboKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otherStudentComboKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_otherStudentComboKeyPressed

    private void studentOtherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentOtherActionPerformed
        if (studentOther.isSelected()) {
            ownStudentCombo.setEnabled(false);
            ownStudentNameText.setEnabled(false);
            otherStudentNameText.setEnabled(true);
            otherStudentCombo.setEnabled(true);
        }
    }//GEN-LAST:event_studentOtherActionPerformed

    private void studentOwnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentOwnActionPerformed
        if (studentOwn.isSelected()) {
            ownStudentCombo.setEnabled(true);
            ownStudentNameText.setEnabled(true);
            otherStudentNameText.setEnabled(false);
            otherStudentCombo.setEnabled(false);
        }
    }//GEN-LAST:event_studentOwnActionPerformed

    private void exitButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButton1ActionPerformed

    private void dateChooserVPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateChooserVPropertyChange
        addAttendanceToTable();
    }//GEN-LAST:event_dateChooserVPropertyChange
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JLabel alreadyLabel;
    private javax.swing.JTable attendanceEditTable;
    private javax.swing.JTable attendanceTable;
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dateChooserM;
    private com.toedter.calendar.JDateChooser dateChooserV;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JLabel dateVLabel;
    private javax.swing.JButton exitButton;
    private javax.swing.JButton exitButton1;
    private javax.swing.JComboBox instructorCombo;
    private javax.swing.JTextField instructorNameText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox otherStudentCombo;
    private javax.swing.JTextField otherStudentNameText;
    private javax.swing.JComboBox ownStudentCombo;
    private javax.swing.JTextField ownStudentNameText;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel studentLabel;
    private javax.swing.JRadioButton studentOther;
    private javax.swing.JRadioButton studentOwn;
    private javax.swing.JComboBox turnCombo;
    private javax.swing.JLabel turnLabel;
    // End of variables declaration//GEN-END:variables
}
