/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dsms.views.view_utilities;

import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

/**
 *
 * @author Minura
 */
public class Calculator extends javax.swing.JFrame {
        String start="";
	int bdecPress=0;
	Double one;
	Double two;
	Double tot;
	int op;
    /**
     * Creates new form Gui
     */
    public Calculator() {
        initComponents();
        setTitle("Calculator");
        setLocationRelativeTo(null);
        setResizable(false);
        txt.setHorizontalAlignment(JTextField.RIGHT);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        bdiv = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        bmul = new javax.swing.JButton();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        bsub = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        bdec = new javax.swing.JButton();
        bequ = new javax.swing.JButton();
        badd = new javax.swing.JButton();
        bclr = new javax.swing.JButton();
        bbck = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(txt)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new java.awt.GridLayout(5, 4));

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn7);

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn8);

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn9);

        bdiv.setText("/");
        bdiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdivActionPerformed(evt);
            }
        });
        jPanel2.add(bdiv);

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn4);

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn5);

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn6);

        bmul.setText("*");
        bmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bmulActionPerformed(evt);
            }
        });
        jPanel2.add(bmul);

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn1);

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn2);

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn3);

        bsub.setText("-");
        bsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsubActionPerformed(evt);
            }
        });
        jPanel2.add(bsub);

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn0);

        bdec.setText(".");
        bdec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bdecActionPerformed(evt);
            }
        });
        jPanel2.add(bdec);

        bequ.setText("=");
        bequ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bequActionPerformed(evt);
            }
        });
        jPanel2.add(bequ);

        badd.setText("+");
        badd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baddActionPerformed(evt);
            }
        });
        jPanel2.add(badd);

        bclr.setText("C");
        bclr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bclrActionPerformed(evt);
            }
        });
        jPanel2.add(bclr);

        bbck.setText("<-");
        bbck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bbckActionPerformed(evt);
            }
        });
        jPanel2.add(bbck);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
                            txt.setText("1");
                            start+=txt.getText();
			    txt.setText(start);         // TODO add your handling code here:
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
                            txt.setText("4");
                            start+=txt.getText();
			    txt.setText(start);             // TODO add your handling code here:
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
                            txt.setText("0");
                            start+=txt.getText();
			    txt.setText(start);         // TODO add your handling code here:
    }//GEN-LAST:event_btn0ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
                            txt.setText("3");
                            start+=txt.getText();
			    txt.setText(start);         // TODO add your handling code here:
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
                            txt.setText("6");
                            start+=txt.getText();
			    txt.setText(start);         // TODO add your handling code here:
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
                            txt.setText("7");
                            start+=txt.getText();
			    txt.setText(start);     // TODO add your handling code here:
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
                            txt.setText("8");
                            start+=txt.getText();
			    txt.setText(start);         // TODO add your handling code here:
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed
                            txt.setText("9");
                            start+=txt.getText();
			    txt.setText(start);         // TODO add your handling code here:
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
                             txt.setText("2");
                            start+=txt.getText();
			    txt.setText(start);         // TODO add your handling code here:
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
                            txt.setText("5");
                            start+=txt.getText();
			    txt.setText(start);         // TODO add your handling code here:
    }//GEN-LAST:event_btn5ActionPerformed

    private void bdivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdivActionPerformed
                   if(op==0 & !"".equals(start)) {
					one=Double.parseDouble(start);
					txt.setText("/");
                                        start+=txt.getText();
			//txt.setText(start);
					op=4;
                               
                    } else { txt.setText(start); }           // TODO add your handling code here:
    }//GEN-LAST:event_bdivActionPerformed

    private void bmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bmulActionPerformed
                if(op==0 & !"".equals(start)) {
					one=Double.parseDouble(start);
					txt.setText("*");
                                        start+=txt.getText();
			//txt.setText(start);
					op=3;
                             
					}
				else { txt.setText(start);
				}  
   
    }//GEN-LAST:event_bmulActionPerformed

    private void bsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsubActionPerformed
                     if(op==0 & !"".equals(start)) {
					one=Double.parseDouble(start);
					txt.setText("-");
                                        start+=txt.getText();
			//txt.setText(start);
					op=2;
                                         
                              
                    }else { txt.setText(start); } // TODO add your handling code here:
    }//GEN-LAST:event_bsubActionPerformed

    private void bdecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bdecActionPerformed
                if(bdecPress==0){
					txt.setText(".");
					start+=txt.getText();
					txt.setText(start);
					bdecPress++;
		}          // TODO add your handling code here:
    }//GEN-LAST:event_bdecActionPerformed

    private void baddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baddActionPerformed
                                if(op==0 & !"".equals(start)) {
					one=Double.parseDouble(start);
					txt.setText("+");
                                        start+=txt.getText();
			//txt.setText(start);
					op=1;
                                         
                               
				}else { txt.setText(start); 
				}        // TODO add your handling code here:
    }//GEN-LAST:event_baddActionPerformed

    private void bequActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bequActionPerformed
                                      if(op!=0 & !"".equals(start)) {
					 txt.setText("=");
                                         start+=txt.getText();
			// txt.setText(start);
                
                                         
					 if(op==1){
							String[] sum = null;
							sum = start.split("\\+");
							two=Double.parseDouble(sum[1].replace("=",""));
							tot=one+two;
							txt.setText(Double.toString(tot));
                                                         start=Double.toString(tot);
                                                        op=0;
					}else if(op==2){
							String[] sum = null;
							sum = start.split("\\-");
							two=Double.parseDouble(sum[1].replace("=",""));
							tot=one-two;
							txt.setText(Double.toString(tot));
                                                         start=Double.toString(tot);
                                                         op=0;
					 }else if(op==3){
							String[] sum = null;
							sum = start.split("\\*");
							two=Double.parseDouble(sum[1].replace("=",""));
							tot=one*two;
							txt.setText(Double.toString(tot));
                                                         start=Double.toString(tot);
                                                         op=0;
					 }else if(op==4){
							String[] sum = null;
							sum = start.split("\\/");
							two=Double.parseDouble(sum[1].replace("=",""));
							tot=one/two;
							txt.setText(Double.toString(tot));
                                                        start=Double.toString(tot);
                                                         op=0;
					 }else { txt.setText("ERROR"); } 
                                     }
    }//GEN-LAST:event_bequActionPerformed

    private void bclrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bclrActionPerformed
                                txt.setText(" ");
				start="";  
                               
    }//GEN-LAST:event_bclrActionPerformed

    private void bbckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bbckActionPerformed
                        String s=txt.getText();
			CharSequence res=s.subSequence(0,s.length() -1);
			txt.setText(res.toString());
                        start=txt.getText();
    }//GEN-LAST:event_bbckActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton badd;
    private javax.swing.JButton bbck;
    private javax.swing.JButton bclr;
    private javax.swing.JButton bdec;
    private javax.swing.JButton bdiv;
    private javax.swing.JButton bequ;
    private javax.swing.JButton bmul;
    private javax.swing.JButton bsub;
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txt;
    // End of variables declaration//GEN-END:variables
}
