/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dsms.views.common_views;

import dsms.common_classes.ComboItemsAdder;
import dsms.common_classes.ComboSearch;
import dsms.controllers.InstructorController;
import dsms.controllers.VehicleClassController;
import dsms.models.Instructor;
import dsms.models.VehicleClassSet;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.StringTokenizer;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class InstructorDetailManagerCommon extends javax.swing.JInternalFrame {

    String instructorId;
    String instructorName;
    String timeIn;
    String timeOut;
    DefaultTableModel dtm;

    public InstructorDetailManagerCommon() {

        initComponents();
        setTitle("Instructor Details");
        
      
        ////////////////////search//////////////////////////////////////
        try {
            ComboItemsAdder.addAllInstructors(instructorComboBox);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(InstructorDetailManagerCommon.class.getName()).log(Level.SEVERE, null, ex);
        }
        ComboSearch.searchCombo(instructorComboBox, "Instructor", "name");
        nameEditText.requestFocus();

       
    }
public void requestFocusForm(){
   instructorComboBox.requestFocus();
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        updateInstructorPanel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        nameText = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        telLabel = new javax.swing.JLabel();
        telephoneText = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        nicLabel = new javax.swing.JLabel();
        nicText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        nameEditLabel = new javax.swing.JLabel();
        nameEditText = new javax.swing.JTextField();
        classLabel = new javax.swing.JLabel();
        classText = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        driLicNoText = new javax.swing.JTextField();
        dlExpireDateText = new javax.swing.JTextField();
        teachLicNoLabel = new javax.swing.JLabel();
        teachDriLicNoText = new javax.swing.JTextField();
        tdlExpireDateLabel = new javax.swing.JLabel();
        tdlExpireDateText = new javax.swing.JTextField();
        dlExpireDateLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        instructorComboBox = new javax.swing.JComboBox();
        jPanel8 = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();
        dateText = new javax.swing.JTextField();

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        updateInstructorPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nameText.setText("Instructor Name  :");

        jLabel5.setText("Date of Registration :");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Detaills"));

        telLabel.setText("Telephone:");

        telephoneText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                telephoneTextKeyPressed(evt);
            }
        });

        addressLabel.setText("Address:");

        nicLabel.setText("NIC no:");

        nicText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nicTextKeyPressed(evt);
            }
        });

        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });
        addressText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                addressTextKeyPressed(evt);
            }
        });

        nameEditLabel.setText("Name:");

        nameEditText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nameEditTextKeyPressed(evt);
            }
        });

        classLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        classLabel.setText("Vehicle classes");

        classText.setEditable(false);
        classText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                classTextKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(telLabel)
                            .addComponent(addressLabel)
                            .addComponent(nicLabel))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nicText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(telephoneText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(nameEditLabel)
                        .addGap(62, 62, 62)
                        .addComponent(nameEditText, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(classLabel)
                        .addGap(18, 18, 18)
                        .addComponent(classText, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameEditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameEditLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telLabel)
                    .addComponent(telephoneText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nicLabel)
                    .addComponent(nicText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("License Details"));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Driving License No:");

        driLicNoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                driLicNoTextKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                driLicNoTextKeyReleased(evt);
            }
        });

        dlExpireDateText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dlExpireDateTextKeyPressed(evt);
            }
        });

        teachLicNoLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        teachLicNoLabel.setText("Teaching License No:");

        teachDriLicNoText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                teachDriLicNoTextKeyPressed(evt);
            }
        });

        tdlExpireDateLabel.setText("TDL Expire date:");

        tdlExpireDateText.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tdlExpireDateTextKeyPressed(evt);
            }
        });

        dlExpireDateLabel.setText("DL Expire date:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/contact256.png"))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dlExpireDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(driLicNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dlExpireDateLabel)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(teachLicNoLabel)
                            .addComponent(tdlExpireDateLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tdlExpireDateText, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(teachDriLicNoText, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(driLicNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dlExpireDateLabel)
                            .addComponent(dlExpireDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(teachLicNoLabel)
                            .addComponent(teachDriLicNoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tdlExpireDateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tdlExpireDateLabel)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        instructorComboBox.setEditable(true);
        instructorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorComboBoxActionPerformed(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/24x24/Cancel.png"))); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jPanel8.add(exitButton);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(nameText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(instructorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameText)
                    .addComponent(jLabel5)
                    .addComponent(instructorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout updateInstructorPanelLayout = new javax.swing.GroupLayout(updateInstructorPanel);
        updateInstructorPanel.setLayout(updateInstructorPanelLayout);
        updateInstructorPanelLayout.setHorizontalGroup(
            updateInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateInstructorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        updateInstructorPanelLayout.setVerticalGroup(
            updateInstructorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updateInstructorPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search instructor details", new javax.swing.ImageIcon(getClass().getResource("/dsms/icons/32x32/vcard.png")), updateInstructorPanel); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void telephoneTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_telephoneTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            addressText.requestFocus();
        }
    }//GEN-LAST:event_telephoneTextKeyPressed

    private void nicTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nicTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            driLicNoText.requestFocus();
        }
    }//GEN-LAST:event_nicTextKeyPressed

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
    }//GEN-LAST:event_addressTextActionPerformed

    private void addressTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTextKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            nicText.requestFocus();
        }
    }//GEN-LAST:event_addressTextKeyPressed

    private void instructorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorComboBoxActionPerformed
        addInstructorData();
    }//GEN-LAST:event_instructorComboBoxActionPerformed

    private void nameEditTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nameEditTextKeyPressed
    }//GEN-LAST:event_nameEditTextKeyPressed

    private void classTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_classTextKeyPressed
    }//GEN-LAST:event_classTextKeyPressed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void driLicNoTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_driLicNoTextKeyPressed
    }//GEN-LAST:event_driLicNoTextKeyPressed

    private void teachDriLicNoTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_teachDriLicNoTextKeyPressed
      
    }//GEN-LAST:event_teachDriLicNoTextKeyPressed

    private void dlExpireDateTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dlExpireDateTextKeyPressed
        
    }//GEN-LAST:event_dlExpireDateTextKeyPressed

    private void tdlExpireDateTextKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tdlExpireDateTextKeyPressed
       
    }//GEN-LAST:event_tdlExpireDateTextKeyPressed

    private void driLicNoTextKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_driLicNoTextKeyReleased
      
    }//GEN-LAST:event_driLicNoTextKeyReleased
   

    private void addInstructorData() {
        try {
            if (instructorComboBox.getSelectedItem() != null) {
                String  instructorSel = instructorComboBox.getSelectedItem().toString();
           StringTokenizer st=new StringTokenizer(instructorSel, "_");          
          String name=st.nextToken();
          instructorId=st.nextToken();
          Instructor instructor=InstructorController.searchInstructor(instructorId);
                if (instructor != null) {
                    addressText.setText(instructor.getAddress());
                    nameEditText.setText(instructor.getName());
                    telephoneText.setText(instructor.getInstructorTel());
                    nicText.setText(instructor.getNic());
                    dateText.setText(instructor.getDateOfRegistration());
                    driLicNoText.setText(instructor.getDriverLicenceNo());
                    dlExpireDateText.setText(instructor.getDriverLicenceExpireDate());
                    teachDriLicNoText.setText(instructor.getTeachingLicenceNo());
                    tdlExpireDateText.setText(instructor.getTeachingLicenceExpireDate());
                    VehicleClassSet vehicleClassSet = VehicleClassController.searchVehicleClassSet(instructor.getClassId());
                    classText.setText(vehicleClassSet.getClassType());
                } else {
                    System.out.println("a");
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(InstructorDetailManagerCommon.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField addressText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel classLabel;
    private javax.swing.JTextField classText;
    private javax.swing.JTextField dateText;
    private javax.swing.JLabel dlExpireDateLabel;
    private javax.swing.JTextField dlExpireDateText;
    private javax.swing.JTextField driLicNoText;
    private javax.swing.JButton exitButton;
    private javax.swing.JComboBox instructorComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel nameEditLabel;
    private javax.swing.JTextField nameEditText;
    private javax.swing.JLabel nameText;
    private javax.swing.JLabel nicLabel;
    private javax.swing.JTextField nicText;
    private javax.swing.JLabel tdlExpireDateLabel;
    private javax.swing.JTextField tdlExpireDateText;
    private javax.swing.JTextField teachDriLicNoText;
    private javax.swing.JLabel teachLicNoLabel;
    private javax.swing.JLabel telLabel;
    private javax.swing.JTextField telephoneText;
    private javax.swing.JPanel updateInstructorPanel;
    // End of variables declaration//GEN-END:variables
}
