/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package dsms.views.report_dialogs;

import dsms.common_classes.CalculationMaker;
import dsms.common_classes.ComboItemsAdder;
import dsms.common_classes.ReportConnector;
import dsms.controllers.TrialPassDetailController;
import dsms.models.TrialPassDetail;
import dsms.views.StudentRegistration;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author User
 */
public class InstructorProgress extends javax.swing.JDialog {

    String instructorName, instructorId;
    DefaultTableModel dtmPassMonth, dtmFailMonth, dtmPassInstructor, dtmFailInstructor, dtmPassComplete, dtmFailComplete, dtmPassYear, dtmFailYear;

    /**
     * Creates new form InstructorProgress
     */
    public InstructorProgress(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
          initComponents();
          setTitle("Instructor Progress");
          setLocationRelativeTo(null);
        try {
          
            ComboItemsAdder.addAllInstructors(instructorCombo);
            ////////////////////////////////
            try {
                ArrayList<TrialPassDetail> passDetails = TrialPassDetailController.searchMonthlyPassed();
                dtmPassComplete = (DefaultTableModel) completePassTable.getModel();
                dtmPassComplete.setRowCount(0);
                for (TrialPassDetail trialPassDetail : passDetails) {
                    dtmPassComplete.addRow(new Object[]{trialPassDetail.getMonthIndex(), trialPassDetail.getMonth() + "   " + trialPassDetail.getYear(), trialPassDetail.getTrialPassed()});
                }
                completePassTotalText.setText(Integer.toString((int) CalculationMaker.colmnAdder(dtmPassComplete, 2)));
                /////////////////////////////////////////////
                ArrayList<TrialPassDetail> failDetails = TrialPassDetailController.searchMonthlyFailed();
                dtmFailComplete = (DefaultTableModel) completeFailTable.getModel();
                dtmFailComplete.setRowCount(0);
                for (TrialPassDetail trialPassDetail : failDetails) {
                    dtmFailComplete.addRow(new Object[]{trialPassDetail.getMonthIndex(), trialPassDetail.getMonth() + "   " + trialPassDetail.getYear(), trialPassDetail.getTrialPassed()});
                }
                completeFailTotalText.setText(Integer.toString((int) CalculationMaker.colmnAdder(dtmFailComplete, 2)));
                //////////////////////////////////////////
                 ArrayList<TrialPassDetail> passDetails1 = TrialPassDetailController.searchInstructorPassed();
                dtmPassYear = (DefaultTableModel) yearPassTable.getModel();
                dtmPassYear.setRowCount(0);
                for (TrialPassDetail trialPassDetail : passDetails1) {
                    dtmPassYear.addRow(new Object[]{trialPassDetail.getInstructorId(), trialPassDetail.getInstructorName(), trialPassDetail.getNoOfStudents()});
                }
                yearPassTotalText.setText(Integer.toString((int) CalculationMaker.colmnAdder(dtmPassYear, 2)));
                /////////////////////////////////////////////
                ArrayList<TrialPassDetail> failDetails1 = TrialPassDetailController.searchInstructorFailed();
                dtmFailYear = (DefaultTableModel) yearFailTable.getModel();
                dtmFailYear.setRowCount(0);
                for (TrialPassDetail trialPassDetail : failDetails1) {
                    dtmFailYear.addRow(new Object[]{trialPassDetail.getInstructorId(), trialPassDetail.getInstructorName(), trialPassDetail.getNoOfStudents()});
                }
                yearFailTotalText.setText(Integer.toString((int) CalculationMaker.colmnAdder(dtmFailYear, 2)));
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(InstructorProgress.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(InstructorProgress.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        monthCombo = new javax.swing.JComboBox();
        jPanel5 = new javax.swing.JPanel();
        tableTitleLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        monthPassTable = new javax.swing.JTable();
        monthPassButton = new javax.swing.JButton();
        monthPassTotalText = new javax.swing.JTextField();
        totalLabel2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        tableTitleLabel3 = new javax.swing.JLabel();
        monthFailButton = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        monthFailTable = new javax.swing.JTable();
        monthFailTotalText = new javax.swing.JTextField();
        totalLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        instructorCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        tableTitleLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        instructorPassTable = new javax.swing.JTable();
        instructorPassButton = new javax.swing.JButton();
        totalLabel = new javax.swing.JLabel();
        instructorPassTotalText = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        tableTitleLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        instructorFailTable = new javax.swing.JTable();
        instructorFailButton = new javax.swing.JButton();
        instructorFailTotalText = new javax.swing.JTextField();
        totalLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        tableTitleLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        completePassTable = new javax.swing.JTable();
        completePassButton = new javax.swing.JButton();
        totalLabel4 = new javax.swing.JLabel();
        completePassTotalText = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        tableTitleLabel5 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        completeFailTable = new javax.swing.JTable();
        completeFailButton = new javax.swing.JButton();
        completeFailTotalText = new javax.swing.JTextField();
        totalLabel5 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        tableTitleLabel6 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        yearPassTable = new javax.swing.JTable();
        yearPassButton = new javax.swing.JButton();
        yearPassTotalText = new javax.swing.JTextField();
        totalLabel6 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        tableTitleLabel7 = new javax.swing.JLabel();
        yearFailButton = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        yearFailTable = new javax.swing.JTable();
        yearFailTotalText = new javax.swing.JTextField();
        totalLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel1.setText("Select month:");

        monthCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        monthCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthComboActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));

        tableTitleLabel2.setBackground(new java.awt.Color(204, 204, 255));
        tableTitleLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tableTitleLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableTitleLabel2.setText("Trial Passed Students ");
        tableTitleLabel2.setOpaque(true);

        monthPassTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "InstructorID", "Name", "NoOfStudents"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(monthPassTable);
        monthPassTable.getColumnModel().getColumn(0).setPreferredWidth(5);
        monthPassTable.getColumnModel().getColumn(1).setPreferredWidth(120);
        monthPassTable.getColumnModel().getColumn(2).setPreferredWidth(10);

        monthPassButton.setText("View Progress");
        monthPassButton.setEnabled(false);
        monthPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthPassButtonActionPerformed(evt);
            }
        });

        monthPassTotalText.setEditable(false);
        monthPassTotalText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        monthPassTotalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthPassTotalTextActionPerformed(evt);
            }
        });

        totalLabel2.setText("Total:");
        totalLabel2.setOpaque(true);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableTitleLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(monthPassButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(monthPassTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableTitleLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(monthPassButton))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalLabel2)
                            .addComponent(monthPassTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(0, 0, 51));

        tableTitleLabel3.setBackground(new java.awt.Color(204, 204, 255));
        tableTitleLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tableTitleLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableTitleLabel3.setText("Trial Failed Students");
        tableTitleLabel3.setOpaque(true);

        monthFailButton.setText("View Statistics");
        monthFailButton.setEnabled(false);
        monthFailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthFailButtonActionPerformed(evt);
            }
        });

        monthFailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "InstructorID", "Name", "NoOfStudents"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(monthFailTable);
        monthFailTable.getColumnModel().getColumn(0).setPreferredWidth(5);
        monthFailTable.getColumnModel().getColumn(1).setPreferredWidth(120);
        monthFailTable.getColumnModel().getColumn(2).setPreferredWidth(10);

        monthFailTotalText.setEditable(false);
        monthFailTotalText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        monthFailTotalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthFailTotalTextActionPerformed(evt);
            }
        });

        totalLabel3.setText("Total:");
        totalLabel3.setOpaque(true);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableTitleLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(monthFailButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(monthFailTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableTitleLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalLabel3)
                        .addComponent(monthFailTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(monthFailButton))
                .addContainerGap())
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(40, Short.MAX_VALUE)))
        );

        jLabel4.setForeground(new java.awt.Color(0, 0, 204));
        jLabel4.setText("(Progress within an year)");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(monthCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addGap(5, 5, 5))
        );

        jTabbedPane1.addTab("By month", jPanel2);

        jPanel9.setBackground(new java.awt.Color(204, 204, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        jLabel2.setText("Select instructor:");

        instructorCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorComboActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("(Progress within an year)");

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));

        tableTitleLabel.setBackground(new java.awt.Color(204, 204, 255));
        tableTitleLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tableTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableTitleLabel.setText("Trial Passed Students ");
        tableTitleLabel.setOpaque(true);

        instructorPassTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index", "Month", "NoOfStudents"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(instructorPassTable);
        instructorPassTable.getColumnModel().getColumn(0).setPreferredWidth(5);
        instructorPassTable.getColumnModel().getColumn(1).setPreferredWidth(120);
        instructorPassTable.getColumnModel().getColumn(2).setPreferredWidth(10);

        instructorPassButton.setText("View Progress");
        instructorPassButton.setEnabled(false);
        instructorPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorPassButtonActionPerformed(evt);
            }
        });

        totalLabel.setText("Total:");
        totalLabel.setOpaque(true);

        instructorPassTotalText.setEditable(false);
        instructorPassTotalText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        instructorPassTotalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorPassTotalTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(instructorPassButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(instructorPassTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 8, Short.MAX_VALUE)
                        .addComponent(instructorPassButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(totalLabel)
                            .addComponent(instructorPassTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(0, 0, 51));

        tableTitleLabel1.setBackground(new java.awt.Color(204, 204, 255));
        tableTitleLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tableTitleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableTitleLabel1.setText("Trial Failed Students");
        tableTitleLabel1.setOpaque(true);

        instructorFailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index", "Month", "NoOfStudents"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(instructorFailTable);
        instructorFailTable.getColumnModel().getColumn(0).setPreferredWidth(5);
        instructorFailTable.getColumnModel().getColumn(1).setPreferredWidth(120);
        instructorFailTable.getColumnModel().getColumn(2).setPreferredWidth(10);

        instructorFailButton.setText("View Statistics");
        instructorFailButton.setEnabled(false);
        instructorFailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorFailButtonActionPerformed(evt);
            }
        });

        instructorFailTotalText.setEditable(false);
        instructorFailTotalText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        instructorFailTotalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorFailTotalTextActionPerformed(evt);
            }
        });

        totalLabel1.setText("Total:");
        totalLabel1.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableTitleLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(instructorFailButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(instructorFailTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableTitleLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(totalLabel1)
                        .addComponent(instructorFailTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(instructorFailButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(instructorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(instructorCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("By instructor", jPanel9);

        jPanel10.setBackground(new java.awt.Color(0, 0, 51));

        tableTitleLabel4.setBackground(new java.awt.Color(204, 204, 255));
        tableTitleLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tableTitleLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableTitleLabel4.setText("Trial Passed Students ");
        tableTitleLabel4.setOpaque(true);

        completePassTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index", "Month", "NoOfStudents"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(completePassTable);
        completePassTable.getColumnModel().getColumn(0).setPreferredWidth(5);
        completePassTable.getColumnModel().getColumn(1).setPreferredWidth(120);
        completePassTable.getColumnModel().getColumn(2).setPreferredWidth(10);

        completePassButton.setText("View Progress");
        completePassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completePassButtonActionPerformed(evt);
            }
        });

        totalLabel4.setText("Total:");
        totalLabel4.setOpaque(true);

        completePassTotalText.setEditable(false);
        completePassTotalText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        completePassTotalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completePassTotalTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableTitleLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(completePassButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(completePassTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableTitleLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(completePassButton)
                    .addComponent(completePassTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel4))
                .addContainerGap())
        );

        jPanel11.setBackground(new java.awt.Color(0, 0, 51));

        tableTitleLabel5.setBackground(new java.awt.Color(204, 204, 255));
        tableTitleLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tableTitleLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableTitleLabel5.setText("Trial Failed Students");
        tableTitleLabel5.setOpaque(true);

        completeFailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Index", "Month", "NoOfStudents"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(completeFailTable);
        completeFailTable.getColumnModel().getColumn(0).setPreferredWidth(5);
        completeFailTable.getColumnModel().getColumn(1).setPreferredWidth(120);
        completeFailTable.getColumnModel().getColumn(2).setPreferredWidth(10);

        completeFailButton.setText("View Statistics");
        completeFailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeFailButtonActionPerformed(evt);
            }
        });

        completeFailTotalText.setEditable(false);
        completeFailTotalText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        completeFailTotalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                completeFailTotalTextActionPerformed(evt);
            }
        });

        totalLabel5.setText("Total:");
        totalLabel5.setOpaque(true);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableTitleLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(completeFailButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(completeFailTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableTitleLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(completeFailButton)
                    .addComponent(totalLabel5)
                    .addComponent(completeFailTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel5.setForeground(new java.awt.Color(0, 0, 204));
        jLabel5.setText("(Progress within an year)");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(49, 49, 49))
        );

        jTabbedPane1.addTab("Monthly Summary", jPanel7);

        jPanel12.setBackground(new java.awt.Color(0, 0, 51));

        tableTitleLabel6.setBackground(new java.awt.Color(204, 204, 255));
        tableTitleLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tableTitleLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableTitleLabel6.setText("Trial Passed Students ");
        tableTitleLabel6.setOpaque(true);

        yearPassTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "InstructorID", "Name", "NoOfStudents"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane8.setViewportView(yearPassTable);
        yearPassTable.getColumnModel().getColumn(0).setPreferredWidth(5);
        yearPassTable.getColumnModel().getColumn(1).setPreferredWidth(120);
        yearPassTable.getColumnModel().getColumn(2).setPreferredWidth(10);

        yearPassButton.setText("View Progress");
        yearPassButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearPassButtonActionPerformed(evt);
            }
        });

        yearPassTotalText.setEditable(false);
        yearPassTotalText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        yearPassTotalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearPassTotalTextActionPerformed(evt);
            }
        });

        totalLabel6.setText("Total:");
        totalLabel6.setOpaque(true);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableTitleLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(yearPassButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(yearPassTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableTitleLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearPassButton)
                    .addComponent(yearPassTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel6))
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(0, 0, 51));

        tableTitleLabel7.setBackground(new java.awt.Color(204, 204, 255));
        tableTitleLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tableTitleLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tableTitleLabel7.setText("Trial Failed Students");
        tableTitleLabel7.setOpaque(true);

        yearFailButton.setText("View Statistics");
        yearFailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearFailButtonActionPerformed(evt);
            }
        });

        yearFailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "InstructorID", "Name", "NoOfStudents"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane9.setViewportView(yearFailTable);
        yearFailTable.getColumnModel().getColumn(0).setPreferredWidth(5);
        yearFailTable.getColumnModel().getColumn(1).setPreferredWidth(120);
        yearFailTable.getColumnModel().getColumn(2).setPreferredWidth(10);

        yearFailTotalText.setEditable(false);
        yearFailTotalText.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        yearFailTotalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearFailTotalTextActionPerformed(evt);
            }
        });

        totalLabel7.setText("Total:");
        totalLabel7.setOpaque(true);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableTitleLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(yearFailButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totalLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(yearFailTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane9))
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tableTitleLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearFailButton)
                    .addComponent(totalLabel7)
                    .addComponent(yearFailTotalText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(87, 87, 87))
        );

        jTabbedPane1.addTab("Instructorwise Summary", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("By instructor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void instructorComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorComboActionPerformed
        String instructorSelected = instructorCombo.getSelectedItem().toString();
        StringTokenizer st = new StringTokenizer(instructorSelected, "_");
        instructorName = st.nextToken();
        instructorId = st.nextToken();

        instructorFailButton.setEnabled(true);
        instructorPassButton.setEnabled(true);

        try {
            ArrayList<TrialPassDetail> passDetails = TrialPassDetailController.searchMonthlyPassed(instructorId);
            dtmPassInstructor = (DefaultTableModel) instructorPassTable.getModel();
            dtmPassInstructor.setRowCount(0);
            for (TrialPassDetail trialPassDetail : passDetails) {
                dtmPassInstructor.addRow(new Object[]{trialPassDetail.getMonthIndex(), trialPassDetail.getMonth() + "   " + trialPassDetail.getYear(), trialPassDetail.getTrialPassed()});
            }
            instructorPassTotalText.setText(Integer.toString((int) CalculationMaker.colmnAdder(dtmPassInstructor, 2)));
            ArrayList<TrialPassDetail> failDetails = TrialPassDetailController.searchMonthlyFailed(instructorId);
            dtmFailInstructor = (DefaultTableModel) instructorFailTable.getModel();
            dtmFailInstructor.setRowCount(0);
            for (TrialPassDetail trialPassDetail : failDetails) {
                dtmFailInstructor.addRow(new Object[]{trialPassDetail.getMonthIndex(), trialPassDetail.getMonth() + "   " + trialPassDetail.getYear(), trialPassDetail.getTrialPassed()});
            }
            instructorFailTotalText.setText(Integer.toString((int) CalculationMaker.colmnAdder(dtmFailInstructor, 2)));
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(InstructorProgress.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_instructorComboActionPerformed

    private void instructorFailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorFailButtonActionPerformed
        try {

            InputStream inputStream = getClass().getResourceAsStream("/dsms/reports/instructor_progress_reports/instructorProgressReport.jrxml");
            //  InputStream inputStream =getClass().getResourceAsStream("dsms/reports/instructor_progress_reports/instructorProgressReport.jrxml");
            HashMap map = new HashMap();
            map.put("instructorId", instructorId);
            map.put("title", tableTitleLabel1.getText());
            map.put("instructorName", instructorName);
            dtmFailInstructor = (DefaultTableModel) instructorFailTable.getModel();

            JasperViewer jv = ReportConnector.sendTable(inputStream, map, dtmFailInstructor);
            ReportConnector.viewInDialog(jv);
        } catch (ClassNotFoundException | SQLException | JRException ex) {
            Logger.getLogger(StudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_instructorFailButtonActionPerformed

    private void instructorPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorPassButtonActionPerformed
        try {

            InputStream inputStream = getClass().getResourceAsStream("/dsms/reports/instructor_progress_reports/instructorProgressReport.jrxml");
            //  InputStream inputStream =getClass().getResourceAsStream("dsms/reports/instructor_progress_reports/instructorProgressReport.jrxml");
            HashMap map = new HashMap();
            map.put("instructorId", instructorId);
            map.put("title", tableTitleLabel.getText());
            map.put("instructorName", instructorName);
            dtmPassInstructor = (DefaultTableModel) instructorPassTable.getModel();

            JasperViewer jv = ReportConnector.sendTable(inputStream, map, dtmPassInstructor);
            ReportConnector.viewInDialog(jv);
        } catch (ClassNotFoundException | SQLException | JRException ex) {
            Logger.getLogger(StudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_instructorPassButtonActionPerformed

    private void monthPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthPassButtonActionPerformed
        try {

            InputStream inputStream = getClass().getResourceAsStream("/dsms/reports/instructor_progress_reports/monthProgressReport.jrxml");
            //  InputStream inputStream =getClass().getResourceAsStream("dsms/reports/instructor_progress_reports/instructorProgressReport.jrxml");
            HashMap map = new HashMap();
            map.put("month", monthCombo.getSelectedItem().toString());

            dtmPassMonth = (DefaultTableModel) monthPassTable.getModel();

            JasperViewer jv = ReportConnector.sendTable(inputStream, map, dtmPassMonth);
            ReportConnector.viewInDialog(jv);
        } catch (ClassNotFoundException | SQLException | JRException ex) {
            Logger.getLogger(StudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_monthPassButtonActionPerformed

    private void monthFailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthFailButtonActionPerformed
        try {

            InputStream inputStream = getClass().getResourceAsStream("/dsms/reports/instructor_progress_reports/monthFailReport.jrxml");
            //  InputStream inputStream =getClass().getResourceAsStream("dsms/reports/instructor_progress_reports/instructorProgressReport.jrxml");
            HashMap map = new HashMap();
            map.put("month", monthCombo.getSelectedItem().toString());

            dtmFailMonth = (DefaultTableModel) monthFailTable.getModel();

            JasperViewer jv = ReportConnector.sendTable(inputStream, map, dtmFailMonth);
            ReportConnector.viewInDialog(jv);
        } catch (ClassNotFoundException | SQLException | JRException ex) {
            Logger.getLogger(StudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_monthFailButtonActionPerformed

    private void monthComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthComboActionPerformed
        try {
            String month = monthCombo.getSelectedItem().toString();
            monthFailButton.setEnabled(true);
            monthPassButton.setEnabled(true);
            ArrayList<TrialPassDetail> passDetails = TrialPassDetailController.searchInstructorPassed(month);
            dtmPassMonth = (DefaultTableModel) monthPassTable.getModel();
            dtmPassMonth.setRowCount(0);
            for (TrialPassDetail trialPassDetail : passDetails) {
                dtmPassMonth.addRow(new Object[]{trialPassDetail.getInstructorId(), trialPassDetail.getInstructorName(), trialPassDetail.getNoOfStudents()});
            }
            monthPassTotalText.setText(Integer.toString((int) CalculationMaker.colmnAdder(dtmPassMonth, 2)));
            ArrayList<TrialPassDetail> failDetails = TrialPassDetailController.searchInstructorFailed(month);
            dtmFailMonth = (DefaultTableModel) monthFailTable.getModel();
            dtmFailMonth.setRowCount(0);
            for (TrialPassDetail trialPassDetail : failDetails) {
                dtmFailMonth.addRow(new Object[]{trialPassDetail.getInstructorId(), trialPassDetail.getInstructorName(), trialPassDetail.getNoOfStudents()});
            }
            monthFailTotalText.setText(Integer.toString((int) CalculationMaker.colmnAdder(dtmFailMonth, 2)));
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(InstructorProgress.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_monthComboActionPerformed

    private void instructorPassTotalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorPassTotalTextActionPerformed
    }//GEN-LAST:event_instructorPassTotalTextActionPerformed

    private void instructorFailTotalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorFailTotalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_instructorFailTotalTextActionPerformed

    private void monthPassTotalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthPassTotalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthPassTotalTextActionPerformed

    private void monthFailTotalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthFailTotalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthFailTotalTextActionPerformed

    private void completePassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completePassButtonActionPerformed
        try {
            InputStream inputStream = getClass().getResourceAsStream("/dsms/reports/instructor_progress_reports/completeProgressReport.jrxml");
            dtmPassComplete = (DefaultTableModel) completePassTable.getModel();

            JasperViewer jv = ReportConnector.sendTable(inputStream, null, dtmPassComplete);
            ReportConnector.viewInDialog(jv);
        } catch (ClassNotFoundException | SQLException | JRException ex) {
            Logger.getLogger(StudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_completePassButtonActionPerformed

    private void completePassTotalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completePassTotalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_completePassTotalTextActionPerformed

    private void completeFailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeFailButtonActionPerformed
        try {
            InputStream inputStream = getClass().getResourceAsStream("/dsms/reports/instructor_progress_reports/completeFailReport.jrxml");
            dtmFailComplete = (DefaultTableModel) completeFailTable.getModel();

            JasperViewer jv = ReportConnector.sendTable(inputStream, null, dtmFailComplete);
            ReportConnector.viewInDialog(jv);
        } catch (ClassNotFoundException | SQLException | JRException ex) {
            Logger.getLogger(StudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_completeFailButtonActionPerformed

    private void completeFailTotalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_completeFailTotalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_completeFailTotalTextActionPerformed

    private void yearPassButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearPassButtonActionPerformed
        try {
            InputStream inputStream = getClass().getResourceAsStream("/dsms/reports/instructor_progress_reports/completeInstructorReport.jrxml");
            dtmPassYear= (DefaultTableModel) yearPassTable.getModel();

            JasperViewer jv = ReportConnector.sendTable(inputStream, null, dtmPassYear);
            ReportConnector.viewInDialog(jv);
        } catch (ClassNotFoundException | SQLException | JRException ex) {
            Logger.getLogger(StudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_yearPassButtonActionPerformed

    private void yearPassTotalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearPassTotalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearPassTotalTextActionPerformed

    private void yearFailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearFailButtonActionPerformed
        try {
            InputStream inputStream = getClass().getResourceAsStream("/dsms/reports/instructor_progress_reports/completeInstructorFailReport.jrxml");
            dtmFailYear = (DefaultTableModel) yearFailTable.getModel();

            JasperViewer jv = ReportConnector.sendTable(inputStream, null, dtmFailYear);
            ReportConnector.viewInDialog(jv);
        } catch (ClassNotFoundException | SQLException | JRException ex) {
            Logger.getLogger(StudentRegistration.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_yearFailButtonActionPerformed

    private void yearFailTotalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearFailTotalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearFailTotalTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InstructorProgress.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                InstructorProgress dialog = new InstructorProgress(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton completeFailButton;
    private javax.swing.JTable completeFailTable;
    private javax.swing.JTextField completeFailTotalText;
    private javax.swing.JButton completePassButton;
    private javax.swing.JTable completePassTable;
    private javax.swing.JTextField completePassTotalText;
    private javax.swing.JComboBox instructorCombo;
    private javax.swing.JButton instructorFailButton;
    private javax.swing.JTable instructorFailTable;
    private javax.swing.JTextField instructorFailTotalText;
    private javax.swing.JButton instructorPassButton;
    private javax.swing.JTable instructorPassTable;
    private javax.swing.JTextField instructorPassTotalText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox monthCombo;
    private javax.swing.JButton monthFailButton;
    private javax.swing.JTable monthFailTable;
    private javax.swing.JTextField monthFailTotalText;
    private javax.swing.JButton monthPassButton;
    private javax.swing.JTable monthPassTable;
    private javax.swing.JTextField monthPassTotalText;
    private javax.swing.JLabel tableTitleLabel;
    private javax.swing.JLabel tableTitleLabel1;
    private javax.swing.JLabel tableTitleLabel2;
    private javax.swing.JLabel tableTitleLabel3;
    private javax.swing.JLabel tableTitleLabel4;
    private javax.swing.JLabel tableTitleLabel5;
    private javax.swing.JLabel tableTitleLabel6;
    private javax.swing.JLabel tableTitleLabel7;
    private javax.swing.JLabel totalLabel;
    private javax.swing.JLabel totalLabel1;
    private javax.swing.JLabel totalLabel2;
    private javax.swing.JLabel totalLabel3;
    private javax.swing.JLabel totalLabel4;
    private javax.swing.JLabel totalLabel5;
    private javax.swing.JLabel totalLabel6;
    private javax.swing.JLabel totalLabel7;
    private javax.swing.JButton yearFailButton;
    private javax.swing.JTable yearFailTable;
    private javax.swing.JTextField yearFailTotalText;
    private javax.swing.JButton yearPassButton;
    private javax.swing.JTable yearPassTable;
    private javax.swing.JTextField yearPassTotalText;
    // End of variables declaration//GEN-END:variables
}
